src/objects/AccountContactRelation.object
<CustomObject>
    <fields>
        <fullName>FinServ__PrimaryGroup__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates a person&apos;s primary group</description>
        <label>Primary Group</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FinServ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates the primary member of a group</description>
        <label>Primary Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FinServ__Rollups__c</fullName>
        <label>Roll-Ups</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                    <default>true</default>
                    <label>All</label>
                </value>
                <value>
                    <fullName>Tasks</fullName>
                </value>
                <value>
                    <fullName>Events</fullName>
                </value>
                <value>
                    <fullName>Financial Accounts</fullName>
                </value>
                <value>
                    <fullName>Assets and Liabilities</fullName>
                </value>
                <value>
                    <fullName>Financial Goals</fullName>
                </value>
                <value>
                    <fullName>Referrals</fullName>
                </value>
                <value>
                    <fullName>Opportunities</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Budget__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount after tax per pay check ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Primary_Owner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budgets (Account)</relationshipLabel>
        <relationshipName>Budgets1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <recordTypes>
        <fullName>Expense_Record_Type</fullName>
        <active>true</active>
        <label>Expense Record Type</label>
    </recordTypes>
    <recordTypes>
        <fullName>Income_Record_Type</fullName>
        <active>true</active>
        <label>Income Record Type</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>401K</fullName>
                </value>
                <value>
                    <fullName>529 Account</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>CD</fullName>
                </value>
                <value>
                    <fullName>Checking</fullName>
                </value>
                <value>
                    <fullName>IRA</fullName>
                </value>
                <value>
                    <fullName>Money Market</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Retail Brokerage</fullName>
                </value>
                <value>
                    <fullName>Roth IRA</fullName>
                </value>
                <value>
                    <fullName>Saving</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>Debt</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinServ__APY__c</fullName>
        <inlineHelpText>Kindly fill the Annual Yield Rate for this Financial Account. Do not leave this blank.</inlineHelpText>
        <label>APY</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>FinServ__Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__FinancialAccountType__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Brokerage</fullName>
                </value>
                <value>
                    <fullName>Discount Brokerage</fullName>
                </value>
                <value>
                    <fullName>CD</fullName>
                </value>
                <value>
                    <fullName>Checking</fullName>
                </value>
                <value>
                    <fullName>Cash Management Account</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Savings</fullName>
                </value>
                <value>
                    <fullName>Mutual Fund</fullName>
                </value>
                <value>
                    <fullName>Fixed Annuity</fullName>
                </value>
                <value>
                    <fullName>Variable Annuity</fullName>
                </value>
                <value>
                    <fullName>Managed Account</fullName>
                </value>
                <value>
                    <fullName>Individual Life</fullName>
                </value>
                <value>
                    <fullName>Term Life</fullName>
                </value>
                <value>
                    <fullName>Variable Life</fullName>
                </value>
                <value>
                    <fullName>Whole Life</fullName>
                </value>
                <value>
                    <fullName>401K</fullName>
                </value>
                <value>
                    <fullName>529 Account</fullName>
                </value>
                <value>
                    <fullName>IRA</fullName>
                </value>
                <value>
                    <fullName>Roth IRA</fullName>
                </value>
                <value>
                    <fullName>Money Market</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinServ__LoanAmount__c</fullName>
        <inlineHelpText>Kindly fill this field for your Loan</inlineHelpText>
        <label>Loan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__LoanEndDate__c</fullName>
        <label>Loan End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FinServ__PaymentAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_yearly_tax_deduction_allowed__c</fullName>
        <label>Max yearly tax deduction allowed ($ )?</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialAccountTransaction__c.object
<CustomObject>
    <description>Represents information about financial account transactions.</description>
    <fields>
        <fullName>FinServ__Amount__c</fullName>
        <description>The amount of each transaction. This field is used for reconciliation.</description>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__FinancialAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account</label>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Account Transactions</relationshipLabel>
        <relationshipName>FinancialAccountTranslations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__TransactionDate__c</fullName>
        <description>The date each transaction occurred. This field is used for reconciliation.</description>
        <label>Transaction Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Financial Account Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialGoal__c.object
<CustomObject>
    <description>Tracks a client&apos;s goal.</description>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>IndustriesIndividual</value>
            </filterItems>
            <filterItems>
                <field>Account.FinServ__IndividualType__c</field>
                <operation>equals</operation>
                <value>Individual</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Financial Goals</relationshipLabel>
        <relationshipName>ClientFinancialGoals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__TargetDate__c</fullName>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FinServ__TargetValue__c</fullName>
        <label>Target Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Goal_Priority__c</fullName>
        <label>Goal Priority</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Priority 1 (must have)</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Priority 2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Priority 3</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Max_yearly_tax_deduction_allowed__c</fullName>
		<defaultValue>0</defaultValue>
        <label>Max yearly tax deduction allowed ($ )?</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Required_Monthly_Saving__c</fullName>
        <label>Required Monthly Saving</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Value__c</fullName>
        <label>Start Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Goal</label>
    <nameField>
        <label>Financial Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Goals</pluralLabel>
    <recordTypes>
        <fullName>CarRecordType</fullName>
        <active>true</active>
        <label>CarRecordType</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ClientDetailApexTest.cls
@isTest
public class ClientDetailApexTest {
    @testsetup
    public static void data(){
        String namespace= NamespaceUtility.returnNamespace();
        String sObject1=namespace+'Budget__c';
        
        //String cId = 'init';
        Account ac = new Account();
        ac.name = 'Test';
        ac.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        insert ac;
        // String cId1 = ac.id;
        
        
        Account ac2 = new Account();
        ac2.name = 'Test2';
        ac2.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        insert ac2;
        
        /*  Account hac = new Account();
hac.name = 'Test2';
hac.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('IndustriesHousehold').getRecordTypeId();
insert hac;


Account hac2 = new Account();
hac2.name = 'Test4';
hac2.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('IndustriesHousehold').getRecordTypeId();
insert hac2;

AccountContactRelation acr = new AccountContactRelation();
acr.accountid = hac.id;
acr.contactid = [select id from contact where accountid =: ac.id].Id;
acr.IsActive = true;
acr.FinServ__PrimaryGroup__c = true;
acr.FinServ__Rollups__c = 'All';
acr.FinServ__Primary__c = true;
insert acr;
String cId2 = hac.id;*/
        
        List<Budget__c> budget=new List<Budget__c>();
        Budget__c income = new Budget__c();
        income.Name = 'test income';
        
        income.Amount__c = 1234;
        income.Primary_Owner__c = ac.Id; 
        income.Start_Date__c = system.today();
        income.End_Date__c = system.today();
        income.RecordTypeId = FinacastUtility.getRecordTypeId('Budget__c', 'Income_Record_Type');
        budget.add(income);
        //insert income;
        
        Budget__c expense = new Budget__c();
        expense.Name = 'test expense';
        expense.Amount__c = 1234;
        expense.Start_Date__c = system.today();
        expense.End_Date__c = system.today();
        expense.Primary_Owner__c = ac.Id;
        expense.RecordTypeId = FinacastUtility.getRecordTypeId('Budget__c','Expense_Record_Type');
        budget.add(expense);
        //insert expense;
        insert budget;
        
        List<FinServ__FinancialAccount__c> fin=new List<FinServ__FinancialAccount__c>();
        FinServ__FinancialAccount__c financial1 = new FinServ__FinancialAccount__c();
        financial1.Name = 'Test Financial Account 1';
        financial1.FinServ__PaymentAmount__c = 5000;
        financial1.FinServ__PrimaryOwner__c= ac.Id;
        financial1.FinServ__LoanAmount__c = 5000;
        financial1.FinServ__APY__c = 4;
        financial1.Max_yearly_tax_deduction_allowed__c =10;
        financial1.RecordTypeId = FinacastUtility.getRecordTypeId('FinServ__FinancialAccount__c', 'LoanAccount');
        financial1.Account_Type__c = 'Loan';
        fin.add(financial1);
        //  insert financial1;
        system.debug('typefin1'+financial1.Account_Type__c);
        
        FinServ__FinancialAccount__c savings1 = new FinServ__FinancialAccount__c();
        savings1.FinServ__PrimaryOwner__c = ac.Id;
        savings1.RecordTypeId = FinacastUtility.getRecordTypeId('FinServ__FinancialAccount__c', 'SavingsAccount');
        savings1.Name = 'Test Savings 1';
        savings1.FinServ__Balance__c = 0;
        savings1.FinServ__APY__c = 3;   
        savings1.FinServ__LoanEndDate__c = Date.today();
        savings1.FinServ__FinancialAccountType__c = 'Savings';
        savings1.Account_Type__c = 'Savings';
        savings1.Max_yearly_tax_deduction_allowed__c =10;
        fin.add(savings1);
        //insert savings1;
        //update savings1;
        system.debug('typefin1'+savings1.RecordTypeId);
        
        FinServ__FinancialAccount__c card = new FinServ__FinancialAccount__c();
        card.Name = 'Test Credit Card 1';
        card.FinServ__Balance__c = 98765;
        card.FinServ__PaymentAmount__c = 5000;
        card.FinServ__PrimaryOwner__c= ac.Id;
        card.FinServ__LoanAmount__c = 5000;
        card.FinServ__APY__c = 4;
        card.Max_yearly_tax_deduction_allowed__c =10;
        card.RecordTypeId = FinacastUtility.getRecordTypeId('FinServ__FinancialAccount__c', 'CreditCard');
        card.FinServ__FinancialAccountType__c  = 'Credit Card';
        card.Account_Type__c = 'Credit Card';
        fin.add(card);
        //insert card;
        
        FinServ__FinancialAccount__c investment = new FinServ__FinancialAccount__c();
        investment.FinServ__PrimaryOwner__c = ac.Id;
        investment.RecordTypeId = FinacastUtility.getRecordTypeId('FinServ__FinancialAccount__c', 'InvestmentAccount');
        investment.Name = 'Test Investment 1';
        investment.FinServ__Balance__c = 98765;
        investment.FinServ__APY__c = 0;   
        investment.Account_Type__c = 'IRA';
        //insert investment;
        fin.add(investment);
        insert fin;
        
        List<FinServ__FinancialAccountTransaction__c> fat=new List<FinServ__FinancialAccountTransaction__c>();
        fat.add(new FinServ__FinancialAccountTransaction__c(FinServ__Amount__c=2000, FinServ__TransactionDate__c=Date.today(),FinServ__FinancialAccount__c=fin[3].Id));
        fat.add(new FinServ__FinancialAccountTransaction__c(FinServ__Amount__c=2000, FinServ__TransactionDate__c=Date.today(),FinServ__FinancialAccount__c=fin[3].Id));
        
        
        insert fat;
        system.debug('typefin1'+card.Account_Type__c);
        FinServ__FinancialGoal__c goals1 = new  FinServ__FinancialGoal__c();
        goals1.FinServ__PrimaryOwner__c = ac.Id;
        goals1.RecordTypeId = FinacastUtility.getRecordTypeId('FinServ__FinancialGoal__c' , 'CarRecordType');
        goals1.Name = 'Test Goal 1';
        goals1.FinServ__TargetValue__c = 10000;
        goals1.FinServ__TargetDate__c = Date.today()+900;
        goals1.Start_Value__c = 2000;
        goals1.Start_Date__c = system.today();
        goals1.Goal_Priority__c = '1';
        goals1.Required_Monthly_Saving__c = 2000;
        goals1.Associated_Account__c = savings1.Id;
        insert goals1;
        
        
        
        //Household Account
        
        /* Budget__c income2 = new Budget__c();
income2.Name = 'test income';
income2.Start_Date__c = system.today();
income2.End_Date__c = system.today();
income2.Amount__c = 4234;
income2.Primary_Owner__c = ac.Id;
income2.HouseHold__c = hac.id;
income2.RecordTypeId = FinacastUtility.getRecordTypeId('Budget__c','Income_Record_Type');
insert income2;

Budget__c expense2 = new Budget__c();
expense2.Name = 'test expense';
expense2.Start_Date__c = system.today();
expense2.End_Date__c = system.today();
expense2.Amount__c = 1234;
expense2.Primary_Owner__c = ac.Id;
expense2.HouseHold__c = hac.id;
expense2.RecordTypeId = FinacastUtility.getRecordTypeId('Budget__c','Income_Record_Type');
insert expense2;

FinServ__FinancialAccount__c financial2 = new FinServ__FinancialAccount__c();
financial2.Name = 'Test Financial Account 1';
financial2.FinServ__PaymentAmount__c = 6000;
financial2.FinServ__PrimaryOwner__c= ac.Id;
financial2.FinServ__LoanAmount__c = 6000;
financial2.FinServ__APY__c = 4;
financial2.FinServ__Household__c = hac.id;
financial2.RecordTypeId = FinacastUtility.getRecordTypeId('FinServ__FinancialAccount__c', 'LoanAccount');
financial2.Account_Type__c = 'Loan';
insert financial2;

FinServ__FinancialAccount__c savings2 = new FinServ__FinancialAccount__c();
savings2.FinServ__PrimaryOwner__c = ac.Id;
savings2.RecordTypeId = FinacastUtility.getRecordTypeId('FinServ__FinancialAccount__c', 'SavingsAccount');
savings2.Name = 'Test Savings 1';
savings2.FinServ__Balance__c = 98765;
savings2.FinServ__Household__c = hac.id;
savings2.FinServ__APY__c = 0;   
savings2.FinServ__LoanEndDate__c = Date.today();
savings2.FinServ__FinancialAccountType__c = 'Savings';
insert savings2;

FinServ__FinancialAccount__c investment = new FinServ__FinancialAccount__c();
investment.FinServ__PrimaryOwner__c = ac.Id;
investment.RecordTypeId = FinacastUtility.getRecordTypeId('FinServ__FinancialAccount__c', 'InvestmentAccount');
investment.Name = 'Test Investment 1';
investment.FinServ__Balance__c = 98765;
investment.FinServ__APY__c = 0;   
investment.Account_Type__c = 'IRA';
insert investment;



FinServ__FinancialAccount__c card2 = new FinServ__FinancialAccount__c();
card2.Name = 'Test Credit Card 1';
card2.FinServ__Balance__c = 98765;
card2.FinServ__PaymentAmount__c = 5000;
card2.FinServ__PrimaryOwner__c= ac.Id;
card2.FinServ__LoanAmount__c = 5000;
card2.FinServ__Household__c = hac.id;
card2.FinServ__APY__c = 4;
card2.RecordTypeId = FinacastUtility.getRecordTypeId('FinServ__FinancialAccount__c', 'CreditCard');
card2.FinServ__FinancialAccountType__c  = 'Credit Card';
insert card2;

list<FinServ__FinancialGoal__c> goals4 = new  list<FinServ__FinancialGoal__c>();
FinServ__FinancialGoal__c goals2 = new  FinServ__FinancialGoal__c();
goals2.FinServ__PrimaryOwner__c = ac.Id;
goals2.RecordTypeId = FinacastUtility.getRecordTypeId('FinServ__FinancialGoal__c' , 'CarRecordType');
goals2.Name = 'Test Goal 1';
goals2.FinServ__TargetValue__c = 10000;
goals2.FinServ__TargetDate__c = Date.today()+900;
goals2.Start_Value__c = 2000;
goals2.FinServ__Household__c = hac.id;
goals2.Goal_Priority__c = '1';
goals2.Start_Date__c = system.today();
goals2.Max_yearly_tax_deduction_allowed__c=5;
goals2.Required_Monthly_Saving__c = 2000;
goals2.Associated_Account__c = savings1.Id;
goals4.add(goals2);
insert goals4;*/
    }
    
    @istest
    public static void createClientDataTest1() {
        Account acc = [select id from Account where name = 'Test'];
        //Account acc2 = [select id from Account where name ='Test2'];
        //Account acc3 = [select id from Account where name = 'Test3'];
        //Account acc4 = [select id from Account where name = 'Test4'];
        //String finId=[select id from FinServ__FinancialAccount__c where name = 'Test Savings 1' limit 1].Id;
        // String finIds=[select id from FinServ__FinancialAccount__c where name = 'Test Credit Card 1' limit 1].Id;
        //String goalId=[select id from FinServ__FinancialGoal__c where name = 'Test Goal 1' limit 1].Id;
        
        test.startTest();
        
        
        ClientDetailApex.createClientData(acc.Id);
        //  ClientDetailApex.getAccounts(acc.Id);
        // ClientDetailApex.getGoals(acc2.Id);
        // ClientDetailApex.getRecordTypeIds();
        // ClientDetailApex.deleteFinAccout(finId);
        //ClientDetailApex.deleteFinAccout(finIds);
        //ClientDetailApex.deleteGoals(goalid);
        //   ClientDetailApex.getNamespace();
        //  ClientDetailApex.isportalEnabled =true;
        //        ClientDetailApex.NumberOfMonths(system.today(), system.today());
        //  ClientDetailApex.NumberOfMonths(null, system.today());
        
        //  ClientDetailApex.curentgoalestimation(250, system.today(), system.today()); 
        test.stopTest();
        System.assertEquals(1,1);
        
    }
    @istest
    public static void createClientDataTest2() {
        Account acc = [select id from Account where name = 'Test2'];
        test.startTest();
        ClientDetailApex.getData(acc.Id);
        
        test.stopTest();
        System.assertEquals(1,1);
        
    }
    @istest
    public static void getGoalsTest() {
        Account acc = [select id from Account where name = 'Test'];
        List<FinServ__FinancialGoal__c> goals=[select id from FinServ__FinancialGoal__c where FinServ__PrimaryOwner__c = :acc.Id];
        list<GoalPerformanceAndMonteCarlo.FinGoalWrapperClass> l;
        test.startTest();
        l= ClientDetailApex.getGoals(acc.Id);
        clientDetailApex.curentgoalestimation(250, system.today(), system.today()); 
        test.stopTest();
        System.assertEquals(goals.size(),l.size());
        
    }
    @istest
    public static void getAccountsTest() {
        Account acc = [select id from Account where name = 'Test'];
        test.startTest();
        
        
        ClientDetailApex.getAccounts(acc.Id);
        test.stopTest();
        
    }
    @istest
    public static void getRecordTypeIdsTest() {
        test.startTest();
        
        
        ClientDetailApex.getRecordTypeIds();
        
        test.stopTest();
        
    }
    
    
    @istest
    public static void getDebtDataTest() {
        Account acc = [select id from Account where name = 'Test'];
        List<FinServ__FinancialAccount__c> debt;
        List<ClientDetailApex.DebtData> l;
        Test.startTest();
        debt= [Select Id,Name, FinServ__LoanAmount__c,FinServ__OpenDate__c from FinServ__FinancialAccount__c where FinServ__PrimaryOwner__c=:acc.Id AND (Account_Type__c='Credit Card' OR Account_Type__c='Loan') ];
        l=ClientDetailApex.getDebtData(acc.Id);
        Test.stopTest();
        System.assertEquals(debt.size(), l.size());
    }
    
    @istest
    public static void getInvestmentDataTest() {
        Account acc = [select id from Account where name = 'Test'];
        Test.startTest();
        ClientDetailApex.getInvestmentdata(acc.Id);
        Test.stopTest();
    }
    @istest
    public static void deleteFinAccoutTest() {
        String finId=[select id from FinServ__FinancialAccount__c where name = 'Test Savings 1' limit 1].Id;
        Test.startTest();
        ClientDetailApex.deleteFinAccout(finId);
        Test.stopTest();
    }
    
    @istest
    public static void getClientTest() {
        Account acc = [select id from Account where name = 'Test'];
        Account a;
        Test.startTest();
        a= ClientDetailApex.getClient(acc.Id);
        Test.stopTest();
        System.assertEquals(acc.Id, a.Id);
    }
    
    @istest
    public static void getRecordTypeIdbyName() {
        String goalId=[select id from FinServ__FinancialGoal__c where name = 'Test Goal 1' limit 1].Id;
        Test.startTest();
        ClientDetailApex.getRecordTypeIdbyName('FinServ__FinancialGoal__c',goalId);
        Test.stopTest();
    }
    
    @istest
    public static void deleteGoalsTest() {
        String goalId=[select id from FinServ__FinancialGoal__c where name = 'Test Goal 1' limit 1].Id;
        Test.startTest();
        ClientDetailApex.deleteGoals(goalId);
        Test.stopTest();
    }
}