src/objects/AccountContactRelation.object
<CustomObject>
    <fields>
        <fullName>FinServ__PrimaryGroup__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates a person&apos;s primary group</description>
        <label>Primary Group</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FinServ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates the primary member of a group</description>
        <label>Primary Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FinServ__Rollups__c</fullName>
        <label>Roll-Ups</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                    <default>true</default>
                    <label>All</label>
                </value>
                <value>
                    <fullName>Tasks</fullName>
                </value>
                <value>
                    <fullName>Events</fullName>
                </value>
                <value>
                    <fullName>Financial Accounts</fullName>
                </value>
                <value>
                    <fullName>Assets and Liabilities</fullName>
                </value>
                <value>
                    <fullName>Financial Goals</fullName>
                </value>
                <value>
                    <fullName>Referrals</fullName>
                </value>
                <value>
                    <fullName>Opportunities</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Budget__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount after tax per pay check ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <recordTypes>
        <fullName>Expense_Record_Type</fullName>
        <active>true</active>
        <label>Expense Record Type</label>
    </recordTypes>
    <recordTypes>
        <fullName>Income_Record_Type</fullName>
        <active>true</active>
        <label>Income Record Type</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>APR__c</fullName>
        <inlineHelpText>Kindly fill the Annual Percentage Rate for this Financial Account. Do not leave this blank.</inlineHelpText>
        <label>APR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>401K</fullName>
                </value>
                <value>
                    <fullName>529 Account</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>CD</fullName>
                </value>
                <value>
                    <fullName>Checking</fullName>
                </value>
                <value>
                    <fullName>IRA</fullName>
                </value>
                <value>
                    <fullName>Money Market</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Retail Brokerage</fullName>
                </value>
                <value>
                    <fullName>Roth IRA</fullName>
                </value>
                <value>
                    <fullName>Saving</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>Debt</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinServ__LoanEndDate__c</fullName>
        <label>Loan End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Max_yearly_tax_deduction_allowed__c</fullName>
        <label>Max yearly tax deduction allowed ($ )?</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialGoal__c.object
<CustomObject>
    <description>Tracks a client&apos;s goal.</description>
    <fields>
        <fullName>Max_yearly_tax_deduction_allowed__c</fullName>
		<defaultValue>0</defaultValue>
        <label>Max yearly tax deduction allowed ($ )?</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Financial Goal</label>
    <nameField>
        <label>Financial Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Goals</pluralLabel>
    <recordTypes>
        <fullName>CarRecordType</fullName>
        <active>true</active>
        <label>CarRecordType</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Scenario__c.object
<CustomObject>
    <fields>
        <fullName>Client_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Scenarios</relationshipLabel>
        <relationshipName>Scenarios</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scenario</label>
    <nameField>
        <label>Scenario Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scenarios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Scenario_Debt__c.object
<CustomObject>
    <fields>
        <fullName>APR__c</fullName>
        <label>APR (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Client_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Scenario Debts</relationshipLabel>
        <relationshipName>Scenario_Debts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Value__c</fullName>
        <label>Current Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
	  <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Scenario Debt</label>
    <nameField>
        <label>Scenario Debt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scenario Debts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Scenario_Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Scenario Expenses</relationshipLabel>
        <relationshipName>Scenario_Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Scenario Expense</label>
    <nameField>
        <label>Scenario Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scenario Expenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Scenario_Goal__c.object
<CustomObject>
    <fields>
        <fullName>Client_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Scenario Goals</relationshipLabel>
        <relationshipName>Scenario_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scenario__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scenario</label>
        <referenceTo>Scenario__c</referenceTo>
        <relationshipLabel>Scenario Goals</relationshipLabel>
        <relationshipName>Scenario_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scenario Goal</label>
    <nameField>
        <label>Scenario Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scenario Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Scenario_Income__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Scenario Incomes</relationshipLabel>
        <relationshipName>Scenario_Incomes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scenario Income</label>
    <nameField>
        <displayFormat>Scenario-Income-{00}</displayFormat>
        <label>Scenario Income Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scenario Incomes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Scenario_Savings__c.object
<CustomObject>
    <fields>
        <fullName>APY__c</fullName>
        <label>APY (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Client_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Scenario Savings</relationshipLabel>
        <relationshipName>Scenario_Savings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Value__c</fullName>
        <label>Current Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Scenario__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scenario</label>
        <referenceTo>Scenario__c</referenceTo>
        <relationshipLabel>Scenario Savings</relationshipLabel>
        <relationshipName>Scenario_Savings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Scenario Saving</label>
    <nameField>
        <label>Scenario_Savings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scenario Savings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/FinacastUtilityTest.cls
@istest
public class FinacastUtilityTest {
    @testsetup
    public static void data(){
        String cId = 'init';
        String FSK ='a22955a47eff160d4ba3ee2bc35581818336cd8d3c73ea789b52c14d6eeba212c6a572097cbb1bf11e29422cefc2f89as';
        
        Account ac = new Account();
        ac.name = 'Test';
        ac.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        insert ac;
        String cId1 = ac.id;
        
        Scenario__c sc=new Scenario__c();
        sc.Client_Id__c=ac.Id;
        insert sc;
        
        Account hac = new Account();
        hac.name = 'Test2';
        hac.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('IndustriesHousehold').getRecordTypeId();
        insert hac;
        
        AccountContactRelation acr = new AccountContactRelation();
        acr.accountid = hac.id;
        acr.contactid = [select id from contact where accountid =: ac.id].Id;
        acr.IsActive = true;
        acr.FinServ__PrimaryGroup__c = true;
        acr.FinServ__Rollups__c = 'All';
        acr.FinServ__Primary__c = true;
        insert acr;
        String cId2 = hac.id;
        
        
        Scenario_Income__c income = new Scenario_Income__c();
        income.Name = 'test income';
        
        income.Amount__c = 1234;
        income.client_ID__c=ac.Id;
        income.Start_Date__c = system.today();
        income.End_Date__c = system.today();
        //income.RecordTypeId = FinacastUtility.getRecordTypeId('Budget__c', 'Income_Record_Type');
        insert income;
        
        Scenario_Expense__c expense = new Scenario_Expense__c();
        expense.Name = 'test expense';
        expense.Amount__c = 1234;
        expense.Start_Date__c = system.today();
        expense.End_Date__c = system.today();
        expense.client_Id__c = ac.Id;
       //xpense.RecordTypeId = FinacastUtility.getRecordTypeId('Budget__c', 'Expense_Record_Type');
        insert expense;
        
        Scenario_Debt__c financial1 = new Scenario_Debt__c();
        financial1.Name = 'Test Financial Account 1';
        financial1.Payment_Amount__c = 5000;
        financial1.Client_Id__c= ac.Id;
        financial1.Current_Value__c = 5000;
        financial1.APR__c = 4;
        //financial1.Max_yearly_tax_deduction_allowed__c =10;
        //financial1.RecordTypeId = FinacastUtility.getRecordTypeId('FinServ__FinancialAccount__c', 'LoanAccount');
      //  financial1.Account_Type__c = 'Loan';
        insert financial1;
      //  system.debug('typefin1'+financial1.Account_Type__c);
        
        Scenario_Savings__c savings1 = new Scenario_Savings__c();
        savings1.Client_Id__c = ac.Id;
       //savings1.RecordTypeId = FinacastUtility.getRecordTypeId('FinServ__FinancialAccount__c', 'SavingsAccount');
        savings1.Name = 'Test Savings 1';
        savings1.Current_Value__c = 0;
        savings1.APY__c = 3;   
        //savings1.FinServ__LoanEndDate__c = Date.today();
        //savings1.FinServ__FinancialAccountType__c = 'Savings';
       // savings1.Account_Type__c = 'Savings';
       // savings1.Max_yearly_tax_deduction_allowed__c =10;
        insert savings1;
        update savings1;
      //  system.debug('typefin1'+savings1.RecordTypeId);
        
        FinServ__FinancialAccount__c card = new FinServ__FinancialAccount__c();
        card.Name = 'Test Credit Card 1';
        card.FinServ__Balance__c = 98765;
        card.FinServ__PaymentAmount__c = 5000;
        card.FinServ__PrimaryOwner__c= ac.Id;
        card.FinServ__LoanAmount__c = 5000;
        card.FinServ__APY__c = 4;
        card.Max_yearly_tax_deduction_allowed__c =10;
        card.RecordTypeId = FinacastUtility.getRecordTypeId('FinServ__FinancialAccount__c', 'CreditCard');
        card.FinServ__FinancialAccountType__c  = 'Credit Card';
        card.Account_Type__c = 'Credit Card';
        insert card;
        
        system.debug('typefin1'+card.Account_Type__c);
        Scenario_Goal__c goals1 = new  Scenario_Goal__c();
        goals1.Client_Id__c = ac.Id;
      //  goals1.RecordTypeId = FinacastUtility.getRecordTypeId('FinServ__FinancialGoal__c' , 'CarRecordType');
        goals1.Name = 'Test Goal 1';
        goals1.Scenario_Target_Amount__c = 10000;
        goals1.Scenario_Target_Date__c = Date.today()+900;
        goals1.Scenario_Current_Amount__c = 2000;
        goals1.Scenario_Start_Date__c = system.today();
        //goals1.Scenario_Goal_Priority__c = '1';
        goals1.Scenario_Monthly_Contribution__c = 2000;
        goals1.Associated_Account__c = savings1.Id;
        insert goals1;
        
        
        
        //Household Account
        
        Budget__c income2 = new Budget__c();
        income2.Name = 'test income';
        income2.Start_Date__c = system.today();
        income2.End_Date__c = system.today();
        income2.Amount__c = 4234;
        income2.Primary_Owner__c = ac.Id;
        income2.HouseHold__c = hac.id;
        income2.RecordTypeId = FinacastUtility.getRecordTypeId('Budget__c', 'Income_Record_Type');
        insert income2;
        
        Budget__c expense2 = new Budget__c();
        expense2.Name = 'test expense';
        expense2.Start_Date__c = system.today();
        expense2.End_Date__c = system.today();
        expense2.Amount__c = 1234;
        expense2.Primary_Owner__c = ac.Id;
        expense2.HouseHold__c = hac.id;
        expense2.RecordTypeId = FinacastUtility.getRecordTypeId('Budget__c', 'Expense_Record_Type');
        insert expense2;
        
        FinServ__FinancialAccount__c financial2 = new FinServ__FinancialAccount__c();
        financial2.Name = 'Test Financial Account 1';
        financial2.FinServ__PaymentAmount__c = 6000;
        financial2.FinServ__PrimaryOwner__c= ac.Id;
        financial2.FinServ__LoanAmount__c = 6000;
        financial2.FinServ__APY__c = 4;
        financial2.FinServ__Household__c = hac.id;
        financial2.RecordTypeId = FinacastUtility.getRecordTypeId('FinServ__FinancialAccount__c', 'LoanAccount');
        financial2.Account_Type__c = 'Loan';
        insert financial2;
        
        FinServ__FinancialAccount__c savings2 = new FinServ__FinancialAccount__c();
        savings2.FinServ__PrimaryOwner__c = ac.Id;
        savings2.RecordTypeId = FinacastUtility.getRecordTypeId('FinServ__FinancialAccount__c', 'SavingsAccount');
        savings2.Name = 'Test Savings 1';
        savings2.FinServ__Balance__c = 98765;
        savings2.FinServ__Household__c = hac.id;
        savings2.FinServ__APY__c = 0;   
        savings2.FinServ__LoanEndDate__c = Date.today();
        savings2.FinServ__FinancialAccountType__c = 'Savings';
        insert savings2;
        
        FinServ__FinancialAccount__c card2 = new FinServ__FinancialAccount__c();
        card2.Name = 'Test Credit Card 1';
        card2.FinServ__Balance__c = 98765;
        card2.FinServ__PaymentAmount__c = 5000;
        card2.FinServ__PrimaryOwner__c= ac.Id;
        card2.FinServ__LoanAmount__c = 5000;
        card2.FinServ__Household__c = hac.id;
        card2.FinServ__APY__c = 4;
        card2.RecordTypeId = FinacastUtility.getRecordTypeId('FinServ__FinancialAccount__c', 'CreditCard');
        card2.FinServ__FinancialAccountType__c  = 'Credit Card';
        insert card2;
        
        list<FinServ__FinancialGoal__c> goals4 = new  list<FinServ__FinancialGoal__c>();
        FinServ__FinancialGoal__c goals2 = new  FinServ__FinancialGoal__c();
        goals2.FinServ__PrimaryOwner__c = ac.Id;
        goals2.RecordTypeId = FinacastUtility.getRecordTypeId('FinServ__FinancialGoal__c' , 'CarRecordType');
        goals2.Name = 'Test Goal 1';
        goals2.FinServ__TargetValue__c = 10000;
        goals2.FinServ__TargetDate__c = Date.today()+900;
        goals2.Start_Value__c = 2000;
        goals2.Start_Date__c = system.today();
        goals2.FinServ__Household__c = hac.id;
        goals2.Goal_Priority__c = '1';
        goals2.Max_yearly_tax_deduction_allowed__c=5;
        goals2.Required_Monthly_Saving__c = 2000;
        goals2.Associated_Account__c = savings1.Id;
        goals4.add(goals2);
       // insert goals4;
    }
    @istest
    public static void TestUtility() {
        Account acc = [select id from Account where name = 'Test'];
       
        Scenario__c sc = [select id from Scenario__c where Client_Id__c =: acc.id];
        list<Scenario_Income__c> income =  [select id from Scenario_Income__c where client_ID__c =: acc.id];
        list<Scenario_Expense__c> expense = [select id from Scenario_Expense__c where client_Id__c =: acc.id];
        System.debug(expense);
        list<Scenario_Savings__c> savings2 = [select id from Scenario_Savings__c where client_Id__c =: acc.id];
        list<Scenario_Debt__c> debt = [select id from Scenario_Debt__c where client_Id__c =: acc.id];
        list<Scenario_Goal__c> goals4 = [select id from Scenario_Goal__c where client_Id__c =: acc.id];
       FinacastUtility.buildScenarioRequestData2(income, expense, savings2, debt, goals4, sc.id, acc.id);
       FinacastUtility.ExceptionHandle(10,'Message Error' , 'StackTrace');
        
    }
    
}