src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FinServ__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Deliquent</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Onboarding</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Client_Adviser_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Adviser_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adviser Id</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Client_Adviser_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Adviser Configurations</relationshipLabel>
        <relationshipName>Client_Adviser_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Adviser Configuration</label>
    <nameField>
        <displayFormat>CAC - {0}</displayFormat>
        <label>Client Advisor Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Adviser Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>FinServ__Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Charge-off</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Paid out</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialGoal__c.object
<CustomObject>
    <description>Tracks a client&apos;s goal.</description>
    <fields>
        <fullName>Annual_Growth_Rate__c</fullName>
        <formula>Associated_Account__r.FinServ__APY__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Annual Growth Rate (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Associated_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Associated Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3 AND 4</booleanFilter>
            <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Scenario_Credit_Cards_Record_Type</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Scenario_Loans_Record_Type</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>LoanAccount</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>CreditCard</value>
            </filterItems>
            <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Goals</relationshipLabel>
        <relationshipName>Financial_Goals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Goal_Amount__c</fullName>
        <label>Current Goal Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>IndustriesIndividual</value>
            </filterItems>
            <filterItems>
                <field>Account.FinServ__IndividualType__c</field>
                <operation>equals</operation>
                <value>Individual</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Financial Goals</relationshipLabel>
        <relationshipName>ClientFinancialGoals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinServ__TargetDate__c</fullName>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FinServ__TargetValue__c</fullName>
        <label>Target Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Goal_Priority__c</fullName>
        <label>Goal Priority</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Priority 1 (must have)</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Priority 2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Priority 3</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Required_Monthly_Saving__c</fullName>
        <label>Required Monthly Saving</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Value__c</fullName>
        <label>Start Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Goal</label>
    <nameField>
        <label>Financial Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/GoalsApexController.cls
public class GoalsApexController {
    
    public static Decimal goalstatus {get; set;}
    public static Decimal totalEstimated = 0;
    @auraEnabled
    public static List<List<Object>> getGoals() {
        List<Client_Adviser_Configuration__c> caConfigList = [select Adviser_Id__c,Client_Id__c,Client_Id__r.name  from Client_Adviser_Configuration__c where adviser_id__c =: UserInfo.getUserId() limit 1];
        Client_Adviser_Configuration__c caConfig = new Client_Adviser_Configuration__c();
        if(caConfigList.size()>0)
        {
            caConfig = caConfigList[0];
        }
        List<FinServ__FinancialGoal__c> retList = [Select id , Name, Associated_Account__r.FinServ__Balance__c,Current_Goal_Amount__c,FinServ__PrimaryOwner__r.name,Goal_Priority__c,Required_Monthly_Saving__c,Start_Value__c, Start_Date__c,Associated_Account__c, FinServ__TargetValue__c,FinServ__TargetDate__c
                                                   from FinServ__FinancialGoal__c where FinServ__PrimaryOwner__c =: caConfig.Client_Id__c ];
        List<String> clientName = new List<String>();
        clientName.add(caConfig.Client_Id__r.name);
        clientName.add(caConfig.Client_Id__c);
        List<List<Object>> returnObjList = new List<List<Object>>();
        try{
            for(FinServ__FinancialGoal__c fgoal : retList)
            {
                fgoal.Current_Goal_Amount__c =(Decimal) getCurrentAmount(fgoal)[0];
                fgoal.FinServ__Status__c = (String)getCurrentAmount(fgoal)[1];
            }
            
            
            returnObjList.add(retList);
            returnObjList.add(clientName);
        }
        catch(Exception e)
        {
            FinacastUtility.ExceptionHandle(e.getLineNumber(), e.getMessage(), e.getStackTraceString());
        }
        return  returnObjList;
    }
    
    @auraEnabled
    public static void deleteGoals(id goalId) {
        try{
            if (Schema.sObjectType.FinServ__FinancialGoal__c.isDeletable()){
                FinServ__FinancialGoal__c goalItem = [Select id from FinServ__FinancialGoal__c where id =:goalId];
                
                delete goalItem;
            }
        }
        catch(Exception e)
        {
            FinacastUtility.ExceptionHandle(e.getLineNumber(), e.getMessage(), e.getStackTraceString());
            
        }
    }
    
    
    @auraEnabled
    public static List<List<Object>> getClientGoals(String clientId) {
        List<List<Object>> returnObjList = new List<List<Object>>();
        
        try{
            List<FinServ__FinancialGoal__c> retList = [Select id , Name, Current_Goal_Amount__c,FinServ__PrimaryOwner__r.name, FinServ__TargetValue__c,FinServ__TargetDate__c
                                                       from FinServ__FinancialGoal__c where FinServ__PrimaryOwner__c =: clientId ];
            List<String> clientName = new List<String>();
            
            clientName.add([select id,name from account where id=: clientId ].name);
            clientName.add([select id,name from account where id=: clientId ].id);
            
            returnObjList.add(retList);
            returnObjList.add(clientName);
        }
        catch(Exception e)
        {
            FinacastUtility.ExceptionHandle(e.getLineNumber(), e.getMessage(), e.getStackTraceString());
            
        }
        return  returnObjList;
    }
    @AuraEnabled
    public static  List<Object> getCurrentAmount( FinServ__FinancialGoal__c retgoal )
    {
        system.debug('hh'+retgoal);
        String status;
        List<FinServ__FinancialGoal__c> allAssocGoals = New List<FinServ__FinancialGoal__c>();
         allAssocGoals = [select name,Current_Goal_Amount__c, Associated_Account__r.FinServ__Balance__c, Start_Value__c,Start_Date__c, Associated_Account__c,Annual_Growth_Rate__c, FinServ__TargetValue__c, FinServ__TargetDate__c, Goal_Priority__c, Required_Monthly_Saving__c from FinServ__FinancialGoal__c where Associated_Account__c=: retgoal.Associated_Account__c and id !=: retgoal.id and Goal_Priority__c <=: retgoal.Goal_Priority__c];
         system.debug('aa'+allAssocGoals);
        if((retgoal.Required_Monthly_Saving__c != 0) && (retgoal.FinServ__TargetValue__c != 0)){
            goalstatus = ((Decimal)curentgoalestimation((double)(retgoal.Required_Monthly_Saving__c), retgoal.Start_Date__c, Date.today())).setScale(2, 
                                                                                                                                                     RoundingMode.HALF_UP) + retgoal.Start_Value__c;
        }else{
            goalstatus = ((Decimal)curentgoalestimation((double)(retgoal.Required_Monthly_Saving__c), retgoal.Start_Date__c, Date.today())).setScale(2, 
                                                                                                                                                     RoundingMode.HALF_UP);
        }
        
        totalEstimated = 0;
        for(FinServ__FinancialGoal__c relgoal : allAssocGoals )
        {
            totalEstimated = totalEstimated + ((Decimal)curentgoalestimation((double)(relgoal.Required_Monthly_Saving__c), relgoal.Start_Date__c, date.today())).setScale(2, 
                                                                                                                                                                          RoundingMode.HALF_UP)+ relgoal.Start_Value__c; 
        }
        if(goalstatus > retgoal.Associated_Account__r.FinServ__Balance__c - totalEstimated){
            system.debug('retgoal.Associated_Account__r.FinServ__Balance__c');
            
            retgoal.Current_Goal_Amount__c = retgoal.Associated_Account__r.FinServ__Balance__c - totalEstimated;
            goalstatus =    goalstatus - retgoal.Current_Goal_Amount__c;
            status = 'Not On Track';
            
        }else {
            goalstatus = goalstatus;
            retgoal.Current_Goal_Amount__c = goalstatus;
            status = 'Track';
            
        }
        List<Object> retList = new List<Object>();
        try{
            retList.add(retgoal.Current_Goal_Amount__c);
            retlist.add(status);
        }
        Catch(Exception e)
        {
            FinacastUtility.ExceptionHandle(e.getLineNumber(), e.getMessage(), e.getStackTraceString());
        }
        return retlist;
    }      
    public static double curentgoalestimation(double emi, Date startDate, Date todaydate ){
        double result = 0;
        Integer months = 0;
        try{
            months = NumberOfMonths(startDate, todaydate);
            if(months >= 1){
                result = months*emi;
            }
        }
        catch(Exception e)
        {
            FinacastUtility.ExceptionHandle(e.getLineNumber(), e.getMessage(), e.getStackTraceString());
        }
        return result;
    }
    public static integer NumberOfMonths(Date startDate, Date endDate){
        
        if(startDate != null && endDate != null){
            Integer months = 0;
            try{
                months = startDate.monthsBetween(endDate);
                
            }
            catch(Exception e){
                FinacastUtility.ExceptionHandle(e.getLineNumber(), e.getMessage(), e.getStackTraceString());
            }
            return months;
        }
        
        else {
            return 0;
        }
    } 
    
    
    
}