src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Public_Group_Id__c</fullName>
        <label>Public Group Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialGoal__c.object
<CustomObject>
    <description>Tracks a client&apos;s goal.</description>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>IndustriesIndividual</value>
            </filterItems>
            <filterItems>
                <field>Account.FinServ__IndividualType__c</field>
                <operation>equals</operation>
                <value>Individual</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Financial Goals</relationshipLabel>
        <relationshipName>ClientFinancialGoals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Financial Goal</label>
    <nameField>
        <label>Financial Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/FinacastGoalHelper.cls
public class FinacastGoalHelper {
    
    public static void shareGoal(List<FinServ__FinancialGoal__c> goalList){
        try{
            List<Id> accountIdList = new List<Id>();
            Map<Id,String> accountGrpMap = new Map<Id,String>();
            List<FinServ__FinancialGoal__share> shareList = new List<FinServ__FinancialGoal__share>();
            for(FinServ__FinancialGoal__c goal : goalList){
                accountIdList.add(goal.FinServ__PrimaryOwner__c);
            }
            
            List<Account>  accountList = [select id , Public_Group_Id__c from account where id in: accountIdList];
            for(Account ac :  accountList)
            {
                if(ac.Public_Group_Id__c != null || ac.Public_Group_Id__c != ''  )
                {
                    accountGrpMap.put(ac.id,ac.Public_Group_Id__c);
                }
            }
            
            for(FinServ__FinancialGoal__c goal : goalList){
                if(accountGrpMap.get(goal.FinServ__PrimaryOwner__c) != null){
                    FinServ__FinancialGoal__share shareGoal = new FinServ__FinancialGoal__share();
                    shareGoal.ParentId = goal.id;
                    shareGoal.UserOrGroupId = accountGrpMap.get(goal.FinServ__PrimaryOwner__c); 
                    shareGoal.RowCause = Schema.FinServ__FinancialGoal__share.RowCause.Manual;
                    shareGoal.AccessLevel = 'Edit';
                    shareList.add(shareGoal);
                }
            }
            insert shareList;
        }
        catch(Exception e)
        {
            FinacastUtility.ExceptionHandle(e.getLineNumber(), e.getMessage(), e.getStackTraceString());
            
        }
    }
    
    public static void updateOwnerforPortalGoals(List<FinServ__FinancialGoal__c> goalList)
    {
        try{
            Map<Id,Id> goalAccountMap = new Map<Id,Id>();
            User us = [select accountid,account.ownerid,contactid from user where id =: UserInfo.getUserId() ];
            for(FinServ__FinancialGoal__c goal : goalList){
                if(us.contactid != null){
                    goal.ownerid = us.account.ownerid;              
                }
            }
        } 
        catch(Exception e)
        {
            FinacastUtility.ExceptionHandle(e.getLineNumber(), e.getMessage(), e.getStackTraceString());
            
        }
    }
    
}