src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Risk_Profile__c</fullName>
        <label>Risk Profile</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Short Term (3.0%)</fullName>
                </value>
                <value>
                    <fullName>Conservative (4.0%)</fullName>
                </value>
                <value>
                    <fullName>Balanced (5.0%)</fullName>
                </value>
                <value>
                    <fullName>Growth (7.0%)</fullName>
                </value>
                <value>
                    <fullName>Aggressive (9.0%)</fullName>
                </value>
                <value>
                    <fullName>Very Aggressive (11.0%)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>FinServ__ModelPortfolio__c</fullName>
        <description>The model asset allocation for this financial account.</description>
        <label>Model Portfolio</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Conservative</fullName>
                </value>
                <value>
                    <fullName>Moderate</fullName>
                </value>
                <value>
                    <fullName>Balanced</fullName>
                </value>
                <value>
                    <fullName>Growth</fullName>
                </value>
                <value>
                    <fullName>Aggressive</fullName>
                </value>
                <value>
                    <fullName>Very Aggressive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Risk_Profile__c</fullName>
        <label>Risk Profile</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aggressive (9.0%)</fullName>
                </value>
                <value>
                    <fullName>Balanced (5.0%)</fullName>
                </value>
                <value>
                    <fullName>Conservative (4.0%)</fullName>
                </value>
                <value>
                    <fullName>Growth (7.0%)</fullName>
                </value>
                <value>
                    <fullName>Short Term (3.0%)</fullName>
                </value>
                <value>
                    <fullName>Very Aggressive (11.0%)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RiskProfileController.cls
public class RiskProfileController {

    @AuraEnabled
    public static void updateInvestmentAccount(String riskResult){
        List<FinServ__FinancialAccount__c> investmentAccount=new List<FinServ__FinancialAccount__c>([Select Id, FinServ__ModelPortfolio__c, Risk_Profile__c from  FinServ__FinancialAccount__c where RecordType.DeveloperName='InvestmentAccount']);
        List<FinServ__FinancialAccount__c> updatedInvestmentAccount=new List<FinServ__FinancialAccount__c>();
        System.debug(investmentAccount.size());
        if(investmentAccount.size()>0){
            for(FinServ__FinancialAccount__c account: investmentAccount){
                account.FinServ__ModelPortfolio__c='Very Aggressive';
                account.Risk_Profile__c='Very Aggressive (11.0%)';
                updatedInvestmentAccount.add(account);
            }
        }
        update updatedInvestmentAccount;
        
    }
}