src/objects/Budget__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Owner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budgets (Account)</relationshipLabel>
        <relationshipName>Budgets1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/GetTransction.cls
public class GetTransction {
    
    @auraEnabled
    public static list<FinServ__FinancialAccount__c> getTransction( string clientId ){   
        Id recTypeId = Schema.getGlobalDescribe().get('FinServ__FinancialAccount__c').getDescribe().getRecordTypeInfosByName().get('Savings Account').getRecordTypeId();
        list<FinServ__FinancialAccount__c> Facclist = new list<FinServ__FinancialAccount__c>();

            Facclist= [select name from FinServ__FinancialAccount__c where FinServ__PrimaryOwner__c=:clientId AND RecordTypeId =:recTypeId];
      
        return Facclist;
    }   
    
    @auraEnabled
    public static list<Budget__c> getBudget(String transction, string clientId ){ 
         String namespace=NamespaceUtility.returnNamespace();
        String objectName=namespace+'Budget__c';
        Id recTypeId = Schema.getGlobalDescribe().get(objectName).getDescribe().getRecordTypeInfosByName().get('Expense Record Type').getRecordTypeId();
        list<Budget__c> Facclist = new list<Budget__c>();
        if(transction =='Expense'){
            Facclist= [select name from Budget__c where Primary_Owner__c=:clientId AND RecordTypeId =:recTypeId];
        }
        system.debug('Facclist'+Facclist);
        return Facclist;
    } 
   
}