src/objects/Budget__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount after tax per pay check ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Income_End_Date__c</fullName>
        <label>End month year</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Income_Start_Date__c</fullName>
        <label>Start month year</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Owner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budgets (Account)</relationshipLabel>
        <relationshipName>Budgets1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scenario_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scenario Id</label>
        <referenceTo>Scenario__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <recordTypes>
        <fullName>Expense_Record_Type</fullName>
        <active>true</active>
        <label>Expense Record Type</label>
    </recordTypes>
    <recordTypes>
        <fullName>Income_Record_Type</fullName>
        <active>true</active>
        <label>Income Record Type</label>
    </recordTypes>
    <recordTypes>
        <fullName>Scenario_Expense_Record_Type</fullName>
        <active>true</active>
        <label>Scenario Expense Record Type</label>
    </recordTypes>
    <recordTypes>
        <fullName>Scenario_Income_Record_Type</fullName>
        <active>true</active>
        <label>Scenario Income Record Type</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>APR__c</fullName>
        <inlineHelpText>Kindly fill the Annual Percentage Rate for this Financial Account. Do not leave this blank.</inlineHelpText>
        <label>APR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>401K</fullName>
                </value>
                <value>
                    <fullName>529 Account</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>CD</fullName>
                </value>
                <value>
                    <fullName>Checking</fullName>
                </value>
                <value>
                    <fullName>IRA</fullName>
                </value>
                <value>
                    <fullName>Money Market</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Retail Brokerage</fullName>
                </value>
                <value>
                    <fullName>Roth IRA</fullName>
                </value>
                <value>
                    <fullName>Saving</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>Debt</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinServ__APY__c</fullName>
        <inlineHelpText>Kindly fill the Annual Yield Rate for this Financial Account. Do not leave this blank.</inlineHelpText>
        <label>APY</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>FinServ__Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__LoanAmount__c</fullName>
        <inlineHelpText>Kindly fill this field for your Loan</inlineHelpText>
        <label>Loan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__LoanEndDate__c</fullName>
        <label>Loan End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FinServ__PaymentAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__PaymentFrequency__c</fullName>
        <label>Payment Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Biweekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quaterly</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                    <isActive>false</isActive>
                    <label>Annual</label>
                </value>
                <value>
                    <fullName>Semiannual</fullName>
                    <isActive>false</isActive>
                    <label>Semiannual</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scenario_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scenario Id</label>
        <referenceTo>Scenario__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <recordTypes>
        <fullName>Scenario_Credit_Cards_Record_Type</fullName>
        <active>true</active>
        <label>Scenario Credit Cards Record Type</label>
    </recordTypes>
    <recordTypes>
        <fullName>Scenario_Loans_Record_Type</fullName>
        <active>true</active>
        <label>Scenario Loans Record Type</label>
    </recordTypes>
    <recordTypes>
        <fullName>Scenario_Savings_Record_Type</fullName>
        <active>true</active>
        <label>Scenario Savings Record Type</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialGoal__c.object
<CustomObject>
    <description>Tracks a client&apos;s goal.</description>
    <fields>
        <fullName>Associated_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Associated Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3 AND 4</booleanFilter>
            <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Scenario_Credit_Cards_Record_Type</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Scenario_Loans_Record_Type</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>LoanAccount</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>CreditCard</value>
            </filterItems>
            <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Goals</relationshipLabel>
        <relationshipName>Financial_Goals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>IndustriesIndividual</value>
            </filterItems>
            <filterItems>
                <field>Account.FinServ__IndividualType__c</field>
                <operation>equals</operation>
                <value>Individual</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Financial Goals</relationshipLabel>
        <relationshipName>ClientFinancialGoals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__TargetDate__c</fullName>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FinServ__TargetValue__c</fullName>
        <label>Target Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Goal_Priority__c</fullName>
        <label>Goal Priority</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Priority 1 (must have)</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Priority 2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Priority 3</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Required_Monthly_Saving__c</fullName>
        <label>Required Monthly Saving</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Scenario_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scenario Id</label>
        <referenceTo>Scenario__c</referenceTo>
        <relationshipLabel>Financial Goals</relationshipLabel>
        <relationshipName>Financial_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Value__c</fullName>
        <label>Start Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Goal</label>
    <nameField>
        <label>Financial Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Goals</pluralLabel>
    <recordTypes>
        <fullName>CarRecordType</fullName>
        <active>true</active>
        <label>CarRecordType</label>
    </recordTypes>
    <recordTypes>
        <fullName>Scenario_Goal_Record_Type</fullName>
        <active>true</active>
        <label>Scenario Goal Record Type</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Scenario__c.object
<CustomObject>
    <fields>
        <fullName>Client_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Scenarios</relationshipLabel>
        <relationshipName>Scenarios</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scenario</label>
    <nameField>
        <label>Scenario Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scenarios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestScenarioApexController.cls
/*
* created by: avneet kaur
* test class for ScenarioContainerApexController
* ***/

@isTest

public class TestScenarioApexController {
    public static Id incomeRecId = FinacastUtility.getRecordTypeId('Budget__c' , 'Scenario_Income_Record_Type');
    public static Id expenseRecId = FinacastUtility.getRecordTypeId('Budget__c' , 'Scenario_Expense_Record_Type');
    public static Id savingsRecId = FinacastUtility.getRecordTypeId('FinServ__FinancialAccount__c' , 'Scenario_Savings_Record_Type');
    public static Id goalsRecId = FinacastUtility.getRecordTypeId('FinServ__FinancialGoal__c' , 'Scenario_Goal_Record_Type');
    public static Id loansRecId = FinacastUtility.getRecordTypeId('FinServ__FinancialAccount__c' , 'Scenario_Loans_Record_Type');
    public static Id cardRecId = FinacastUtility.getRecordTypeId('FinServ__FinancialAccount__c' , 'Scenario_Credit_Cards_Record_Type');
    public static Id incomeTypeId = FinacastUtility.getRecordTypeId('Budget__c' , 'Income_Record_Type');
    public static Id expenseTypeId = FinacastUtility.getRecordTypeId('Budget__c' , 'Expense_Record_Type');
    public static Id savingsTypeId = FinacastUtility.getRecordTypeId('FinServ__FinancialAccount__c' , 'SavingsAccount');
    public static Id goalsTypeId = FinacastUtility.getRecordTypeId('FinServ__FinancialGoal__c' , 'CarRecordType');
    public static Id loansTypeId = FinacastUtility.getRecordTypeId('FinServ__FinancialAccount__c' , 'LoanAccount');
    public static Id cardTypeId = FinacastUtility.getRecordTypeId('FinServ__FinancialAccount__c' , 'CreditCard');
    public static Id hhTypeId = FinacastUtility.getRecordTypeId('Account' , 'IndustriesHousehold');
    
    
    @TestSetup
    static void testData() {
        Id recTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.RecordTypeId = recTypeId;
        insert acc;
        
        Account acc2 = new Account();
        acc2.Name = 'Test2 Account';
        acc2.RecordTypeId = recTypeId;
        insert acc2;
        
        Scenario__c scene = new Scenario__c();
        scene.Name = 'Test Scenario';
        scene.Client_Id__c = acc.id;
        insert scene;
        
        Scenario__c scene2 = new Scenario__c();
        scene2.Name = 'Test Scenario 2';
        scene2.Client_Id__c = acc.id;
        insert scene2;
        
        Budget__c income1 = new Budget__c();
        income1.Name = 'Test Income 1';
        income1.Income_Start_Date__c=system.today();
        income1.Income_End_Date__c=system.today();
        income1.Primary_Owner__c = acc.id;
        income1.RecordTypeId = incomeRecId;
        income1.Scenario_Id__c = scene.Id;
        income1.Amount__c = 178;
        insert income1;
        
        Budget__c income2 = new Budget__c();
        income2.Name = 'Test Income 2';
        income2.Income_Start_Date__c=system.today();
        income2.Income_End_Date__c=system.today();
        income2.Primary_Owner__c = acc2.id;
        income2.RecordTypeId = incomeTypeId;
        income2.Scenario_Id__c = scene2.Id;
        insert income2;
        
        Budget__c income3 = new Budget__c();
        income3.Name = 'Test Income 3';
        income3.Primary_Owner__c = acc.id;
        income3.Income_Start_Date__c=system.today();
        income3.Income_End_Date__c=system.today();
        income3.RecordTypeId = incomeTypeId;
        income3.Amount__c = 1234;
        insert income3;
        
        Budget__c expense1 = new Budget__c();
        expense1.Name = 'Test Expense 1';
        expense1.Income_Start_Date__c=system.today();
        expense1.Income_End_Date__c=system.today();
        expense1.Primary_Owner__c = acc.Id;
        expense1.Scenario_Id__c = scene.Id;
        expense1.RecordTypeId = expenseRecId;
        expense1.Amount__c = 1234;
        insert expense1;
        
        Budget__c expense2 = new Budget__c();
        expense2.Name = 'Test Expense 2';
        expense2.Primary_Owner__c = acc2.Id;
        expense2.Scenario_Id__c = scene2.Id;
        expense2.Income_Start_Date__c=system.today();
        expense2.Income_End_Date__c=system.today();
        expense2.RecordTypeId = expenseTypeId;
        insert expense2;
        
        Budget__c expense3 = new Budget__c();
        expense3.Name = 'Test Expense 3';
        expense3.Primary_Owner__c = acc.Id;
        expense3.Amount__c = 1212;
        expense3.Income_Start_Date__c=system.today();
        expense3.Income_End_Date__c=system.today();
        expense3.RecordTypeId = expenseTypeId;
        insert expense3;
        
        FinServ__FinancialAccount__c savings1 = new FinServ__FinancialAccount__c();
        savings1.FinServ__PrimaryOwner__c = acc.Id;
        savings1.Scenario_Id__c = scene.Id;
        savings1.RecordTypeId = savingsRecId;
        savings1.Name = 'Test Savings 1';
        savings1.FinServ__Balance__c = 98765;
        savings1.FinServ__APY__c = 3;   
        savings1.FinServ__LoanEndDate__c = Date.today();
        savings1.Account_Type__c = 'Saving';
        insert savings1;
        
        FinServ__FinancialAccount__c savings2 = new FinServ__FinancialAccount__c();
        savings2.FinServ__PrimaryOwner__c = acc.Id;
        savings2.RecordTypeId = savingsRecId;
        savings2.Name = 'Test Savings 2';
        savings2.FinServ__Balance__c = 98765;
        savings2.FinServ__APY__c = 3;   
        savings2.FinServ__LoanEndDate__c = Date.today();
        savings2.Account_Type__c = 'Saving';
        insert savings2;
        
        
        FinServ__FinancialGoal__c goals1 = new  FinServ__FinancialGoal__c();
        goals1.FinServ__PrimaryOwner__c = acc.Id;
        goals1.Scenario_Id__c = scene.Id;
        goals1.RecordTypeId = goalsRecId;
        goals1.Name = 'Test Goal 1';
        goals1.FinServ__TargetValue__c = 10000;
        goals1.FinServ__TargetDate__c = Date.today()+900;
        goals1.Start_Value__c = 2000;
        goals1.Goal_Priority__c = '1';
        goals1.Required_Monthly_Saving__c = 2000; 
        goals1.Associated_Account__c = savings1.Id;
        insert goals1;
        
        FinServ__FinancialGoal__c goals2 = new  FinServ__FinancialGoal__c();
        goals2.FinServ__PrimaryOwner__c = acc.Id;
        goals2.RecordTypeId = goalsTypeId;
        goals2.Name = 'Test Goal 2';
        goals2.FinServ__TargetValue__c = 10000;
        goals2.FinServ__TargetDate__c = Date.today()+900;
        goals2.Start_Value__c = 2000;
        goals2.Goal_Priority__c = '1';
        goals2.Required_Monthly_Saving__c = 2000; 
        goals2.Associated_Account__c = savings2.Id;
        insert goals2;
        
        FinServ__FinancialAccount__c loan1 = new FinServ__FinancialAccount__c();
        loan1.FinServ__PrimaryOwner__c = acc.Id;
        loan1.Scenario_Id__c = scene.Id;
        loan1.RecordTypeId = loansRecId;
        loan1.Name = 'Test Loan 1';
        loan1.APR__c = 5;
        loan1.FinServ__LoanAmount__c = 10000;
        loan1.FinServ__PaymentFrequency__c = 'Monthly';
        loan1.FinServ__PaymentAmount__c = 11000;
        loan1.Account_Type__c = 'Loan';
        insert loan1;
        
        FinServ__FinancialAccount__c loan2 = new FinServ__FinancialAccount__c();
        loan2.FinServ__PrimaryOwner__c = acc.Id;
        loan2.RecordTypeId = loansTypeId;
        loan2.Name = 'Test Loan 2';
        loan2.Account_Type__c = 'Loan';
        loan2.APR__c = 5;
        loan2.FinServ__LoanAmount__c = 10000;
        loan2.FinServ__PaymentFrequency__c = 'Monthly';
        loan2.FinServ__PaymentAmount__c = 11000;
        insert loan2;
        
        FinServ__FinancialAccount__c loan3 = new FinServ__FinancialAccount__c();
        loan3.FinServ__PrimaryOwner__c = acc.Id;
        loan3.RecordTypeId = loansTypeId;
        loan3.Name = 'Test Loan 3';
        loan3.Account_Type__c = 'Loan';
        loan3.APR__c = 5;
        loan3.FinServ__LoanAmount__c = 10000;
        loan3.FinServ__PaymentFrequency__c = 'Monthly';
        loan3.FinServ__PaymentAmount__c = 11000;
        insert loan3;
        
        FinServ__FinancialAccount__c card1 = new FinServ__FinancialAccount__c();
        card1.FinServ__PrimaryOwner__c = acc.Id;
        card1.Scenario_Id__c = scene.Id;
        card1.RecordTypeId = cardRecId;
        card1.Name = 'Test Credit Card 1';
        card1.FinServ__LoanAmount__c = 9000;
        card1.APR__c = 2;
        card1.Account_Type__c = 'Credit Card';
        insert card1;
        
        FinServ__FinancialAccount__c card2 = new FinServ__FinancialAccount__c();
        card2.FinServ__PrimaryOwner__c = acc.Id;
        card2.RecordTypeId = cardTypeId;
        card2.Name = 'Test Credit Card 2';
        card2.FinServ__LoanAmount__c = 9000;
        card2.APR__c = 2;
        card2.FinServ__FinancialAccountType__c ='Credit Card'; 
        card2.Account_Type__c = 'Credit Card';
        card2.FinServ__Balance__c=1000;
        
        insert card2;
    }
    
    static testMethod void testScenario() {
        
       
        Account accVar1 = [select id from Account where name = 'Test Account'];
        Account accVar2 = [select id from Account where name = 'Test2 Account'];
        Scenario__c sceneVar1 = [select id from Scenario__c where name = 'Test Scenario'];
        Scenario__c sceneVar2 = [select id from Scenario__c where name = 'Test Scenario 2'];
        Budget__c incomeVar1 = [select Id from Budget__c where Name = 'Test Income 1' ];
        Budget__c expenseVar1 = [select Id from Budget__c where Name = 'Test Expense 1'];
        FinServ__FinancialGoal__c goalVar1 = [select id from FinServ__FinancialGoal__c where Name = 'Test Goal 1'];
        FinServ__FinancialAccount__c loanVar1 = [select id from FinServ__FinancialAccount__c where Name = 'Test Loan 1'];
        FinServ__FinancialAccount__c cardVar1 = [select id from FinServ__FinancialAccount__c where Name = 'Test Credit Card 1'];
        FinServ__FinancialAccount__c savingVar1 = [select id from FinServ__FinancialAccount__c where Name = 'Test Savings 1'];
        
        test.startTest();
        // FinacastBudgetHelper.shareBudget(bdId);
        ScenarioContainerApexController.getUserScenarios(accVar1.Id, sceneVar1.Id);
        ScenarioContainerApexController.getUserScenarios('init', 'init');
        ScenarioContainerApexController.getUserScenarios(accVar1.Id, null);
        ScenarioContainerApexController.getUserScenarios(accVar2.Id, sceneVar2.Id);
         ScenarioContainerApexController.saveRecord('scenario 1', accVar1.Id, 'scenario', null, 0, 0, null); 
        ScenarioContainerApexController.saveRecord('scene income 1',accVar1.Id, 'income save',sceneVar1.Id, 1234, 0, 'init');
        ScenarioContainerApexController.saveRecord('Test Income 1',accVar1.Id, 'income save',sceneVar1.Id, 1234, 0, incomeVar1.Id);
        ScenarioContainerApexController.saveRecord('scene expense 1',accVar1.Id, 'expense save',sceneVar1.Id, null, 1234, 'init');
        

        test.stopTest();
        
        System.assertEquals('1', '1');
    }
    static testMethod void testScenario1() 
    {
       
       Account accVar1 = [select id from Account where name = 'Test Account'];
        Account accVar2 = [select id from Account where name = 'Test2 Account'];
        Scenario__c sceneVar1 = [select id from Scenario__c where name = 'Test Scenario'];
        Scenario__c sceneVar2 = [select id from Scenario__c where name = 'Test Scenario 2'];
        Budget__c incomeVar1 = [select Id from Budget__c where Name = 'Test Income 1' ];
        Budget__c expenseVar1 = [select Id from Budget__c where Name = 'Test Expense 1'];
        FinServ__FinancialGoal__c goalVar1 = [select id from FinServ__FinancialGoal__c where Name = 'Test Goal 1'];
        FinServ__FinancialAccount__c loanVar1 = [select id from FinServ__FinancialAccount__c where Name = 'Test Loan 1'];
        FinServ__FinancialAccount__c cardVar1 = [select id from FinServ__FinancialAccount__c where Name = 'Test Credit Card 1'];
        FinServ__FinancialAccount__c savingVar1 = [select id from FinServ__FinancialAccount__c where Name = 'Test Savings 1']; 
        
        test.startTest();
        DateTime d = Date.today()+900;
        String tarDate = d.format('YYYY-MM-dd');
        ScenarioContainerApexController.getAmtContri (savingVar1.Id, 1232, tarDate, 11111);
        ScenarioContainerApexController.getRecordTypeId('goal button');
        ScenarioContainerApexController.getRecordTypeId('loan button');
        ScenarioContainerApexController.getRecordTypeId('saving button');
        ScenarioContainerApexController.getRecordTypeId('credit card button');
        ScenarioContainerApexController.saveRecord('scene expense 1',accVar1.Id, 'expense save',sceneVar1.Id, null,1234, expenseVar1.Id);
        ScenarioContainerApexController.deleteRecord(accVar1.Id,sceneVar1.Id, goalVar1.Id, 'goal button');
        
        ScenarioContainerApexController.deleteRecord(accVar1.Id,sceneVar1.Id, loanVar1.Id, 'loan button');
        ScenarioContainerApexController.deleteRecord(accVar1.Id,sceneVar1.Id, sceneVar1.Id, 'scenario');
        
        ScenarioContainerApexController.deleteRecord(accVar1.Id,sceneVar1.Id, goalVar1.Id, 'goal button');
        ScenarioContainerApexController.deleteRecord(accVar1.Id,sceneVar1.Id, loanVar1.Id, 'loan button');
        ScenarioContainerApexController.deleteRecord(accVar1.Id,sceneVar1.Id, cardVar1.Id, 'credit card button');
        ScenarioContainerApexController.deleteRecord(accVar1.Id,sceneVar1.Id, savingVar1.Id, 'saving button');
        
        
        
        ScenarioContainerApexController.deleteRecord (accVar1.Id, sceneVar1.Id, savingVar1.Id, 'saving button'); 
        ScenarioContainerApexController.getAmtContri (savingVar1.Id, 1232, tarDate, 11111);
        ScenarioContainerApexController.getAmtContri (savingVar1.Id, null, tarDate, 11111);
        ScenarioContainerApexController.getRecordTypeId('goal button');
        ScenarioContainerApexController.getRecordTypeId('loan button');
        ScenarioContainerApexController.getRecordTypeId('saving button');
        ScenarioContainerApexController.getRecordTypeId('credit card button');        
        ScenarioContainerApexController.deleteRecord (accVar1.Id, sceneVar1.Id, goalVar1.Id, 'goal button');
        ScenarioContainerApexController.deleteRecord (accVar1.Id, sceneVar2.Id, loanVar1.Id, 'loan button');
        ScenarioContainerApexController.deleteRecord (accVar1.Id, sceneVar1.Id, savingVar1.Id, 'saving button');
        test.stopTest();
    }
}