src/objects/Budget__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Owner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budgets (Account)</relationshipLabel>
        <relationshipName>Budgets1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialAccountTransaction__c.object
<CustomObject>
    <description>Represents information about financial account transactions.</description>
    <fields>
        <fullName>Budget_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Category</label>
        <referenceTo>Budget__c</referenceTo>
        <relationshipLabel>Financial Account Transactions</relationshipLabel>
        <relationshipName>Financial_Account_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__Amount__c</fullName>
        <description>The amount of each transaction. This field is used for reconciliation.</description>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__TransactionDate__c</fullName>
        <description>The date each transaction occurred. This field is used for reconciliation.</description>
        <label>Transaction Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FinServ__TransactionType__c</fullName>
        <description>Type of the transaction. This field is used to determine whether the transaction falls under income or expense. Also used in reconciliation logic.</description>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Debit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Financial Account Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CashFolwGraphIncomeTest.cls
@isTest
public class CashFolwGraphIncomeTest {
    @isTest
    static void testGraph(){
        Account acc = new Account(Name='TestGraph');
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        insert acc;
        
        Budget__c   bg = new Budget__c();
        bg.name = 'Test';  
        bg.Primary_Owner__c=acc.id;
        insert bg;
        
        
        
        List<FinServ__FinancialAccountTransaction__c> fat = new List<FinServ__FinancialAccountTransaction__c>();
        FinServ__FinancialAccountTransaction__c datevalue = new FinServ__FinancialAccountTransaction__c(Budget_Category__c=bg.id,FinServ__Amount__c=23421, FinServ__TransactionDate__c=Date.today().addDays(-30), FinServ__TransactionType__c='Debit');
        FinServ__FinancialAccountTransaction__c datevalue1 = new FinServ__FinancialAccountTransaction__c(Budget_Category__c=bg.id,FinServ__Amount__c=23421, FinServ__TransactionDate__c=Date.today().addDays(-60), FinServ__TransactionType__c='Credit');
        
        fat.add(datevalue);
        fat.add(datevalue1);
        insert fat;
        
        
        
        test.startTest();
        System.assert(bg.id != null);
        CashFolwGraphIncome.getTransctionLoanSavingAmount(bg.id);
        
        test.stopTest();
    }

}