src/objects/Budget__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount after tax per pay check ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Semi Monthly</fullName>
                </value>
                <value>
                    <fullName>Bi-Weekly</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HouseHold__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HouseHold</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budgets (HouseHold)</relationshipLabel>
        <relationshipName>Budgets_HouseHold</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <formula>CASE(MONTH( Income_Start_Date__c ), 1, &quot;January&quot;, 2, &quot;February&quot;, 3, &quot;March&quot;,  4, &quot;April&quot;,  5, &quot;May&quot;,  6, &quot;June&quot;, 7, &quot;July&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;October&quot;, 11, &quot;November&quot;, 12, &quot;December&quot;, &quot;None&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Month</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Owner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budgets (Account)</relationshipLabel>
        <relationshipName>Budgets1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Priority 1 - Must Have</fullName>
                </value>
                <value>
                    <fullName>Priority 2</fullName>
                </value>
                <value>
                    <fullName>Priority 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Approximate total income tax rate (%)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Yearly_growth__c</fullName>
        <label>Yearly growth(%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <recordTypes>
        <fullName>Expense_Record_Type</fullName>
        <active>true</active>
        <label>Expense Record Type</label>
    </recordTypes>
    <recordTypes>
        <fullName>Income_Record_Type</fullName>
        <active>true</active>
        <label>Income Record Type</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>APR__c</fullName>
        <inlineHelpText>Kindly fill the Annual Percentage Rate for this Financial Account. Do not leave this blank.</inlineHelpText>
        <label>APR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>FinServ__Household__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Household that this financial account rolls up to.</description>
        <label>Household</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Household</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Household Financial Accounts</relationshipLabel>
        <relationshipName>HouseholdFinancialAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__LoanAmount__c</fullName>
        <inlineHelpText>Kindly fill this field for your Loan</inlineHelpText>
        <label>Loan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__LoanEndDate__c</fullName>
        <label>Loan End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FinServ__PaymentAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__PaymentFrequency__c</fullName>
        <label>Payment Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Biweekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quaterly</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                    <isActive>false</isActive>
                    <label>Annual</label>
                </value>
                <value>
                    <fullName>Semiannual</fullName>
                    <isActive>false</isActive>
                    <label>Semiannual</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialAccountTransaction__c.object
<CustomObject>
    <description>Represents information about financial account transactions.</description>
    <fields>
        <fullName>Budget_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Category</label>
        <referenceTo>Budget__c</referenceTo>
        <relationshipLabel>Financial Account Transactions</relationshipLabel>
        <relationshipName>Financial_Account_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Destination_Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>SavingsAccount</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>LoanAccount</value>
            </filterItems>
            <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Account Transactions (Destination Financial Account)</relationshipLabel>
        <relationshipName>Financial_Account_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__Amount__c</fullName>
        <description>The amount of each transaction. This field is used for reconciliation.</description>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__FinancialAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account</label>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Account Transactions</relationshipLabel>
        <relationshipName>FinancialAccountTranslations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__TransactionDate__c</fullName>
        <description>The date each transaction occurred. This field is used for reconciliation.</description>
        <label>Transaction Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Financial Account Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialGoal__c.object
<CustomObject>
    <description>Tracks a client&apos;s goal.</description>
    <fields>
        <fullName>Associated_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Associated Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3 AND 4</booleanFilter>
            <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Scenario_Credit_Cards_Record_Type</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Scenario_Loans_Record_Type</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>LoanAccount</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>CreditCard</value>
            </filterItems>
            <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Goals</relationshipLabel>
        <relationshipName>Financial_Goals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__Household__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Household that this goal is associated with.</description>
        <label>Household</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Household</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Household Financial Goals</relationshipLabel>
        <relationshipName>HouseholdFinancialGoals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>IndustriesIndividual</value>
            </filterItems>
            <filterItems>
                <field>Account.FinServ__IndividualType__c</field>
                <operation>equals</operation>
                <value>Individual</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Financial Goals</relationshipLabel>
        <relationshipName>ClientFinancialGoals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Required_Monthly_Saving__c</fullName>
        <label>Required Monthly Saving</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Value__c</fullName>
        <label>Start Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Goal</label>
    <nameField>
        <label>Financial Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/IncomeGraphController.cls
public with sharing class IncomeGraphController {
    public class wrapIncome{
        @AuraEnabled
        List<Budget__c> incomeRecList{get;set;}
        @AuraEnabled
        public String totalIncome;
        @AuraEnabled
        List<Budget__c> expenseRecList{get;set;}
        @AuraEnabled
        List<FinServ__FinancialAccount__c> loanRecList{get;set;}
        @AuraEnabled
        List<FinServ__FinancialGoal__c> goalRecList{get;set;}
        @AuraEnabled
        public String totalExpense;
        @AuraEnabled
        public String totalLoan;
        @AuraEnabled
        public String totalGoal;
        @AuraEnabled
        public Account client; 
        @AuraEnabled
        public Boolean isportalUser;
        @AuraEnabled
        public Double totalTransaction;           
        @AuraEnabled
        public Map<Id, Double> transAmount;
        @AuraEnabled
        public Map<Id, Double> transAmountExpense;
        @AuraEnabled
        public Map<Id, Double> transAmountLoan;
        @AuraEnabled
        public Map<Id, String> sumOfIncome;
        @AuraEnabled
        public Map<Id, String> sumOfExpense;
        @AuraEnabled
        public Map<Id, String> sumOfLoan;
        @AuraEnabled
        public String TransSumValInc ;
        @AuraEnabled
        public String TransSumValExp ;
        @AuraEnabled
        public String TransSumValLoan ;
        
        public wrapIncome(List<Budget__c> incomeTypeRec , String incomeSum, List<Budget__c> expenseTypeRec,String expenseSum ,
                          List<FinServ__FinancialGoal__c> goalTypeRec, String goalSum,List<FinServ__FinancialAccount__c>loanTypeRec ,
                          String loanSum,Account clnt,Boolean isPortalEnabled , Double transactionSum , Map<Id , Double> transactionAmount,
                          Map<Id , Double> transactionAmountExpense, Map<Id , Double> transactionAmountLoan,
                          Map<Id, String> sumOfIncomes,Map<Id, String> sumOfExpenses,Map<Id, String> sumOfLoans,
                          String transInc , String transExp , String transLoan)
        {            
            incomeRecList=incomeTypeRec;
            totalIncome = incomeSum;
            expenseRecList = expenseTypeRec;
            totalExpense = expenseSum ;
            loanRecList = loanTypeRec;
            totalLoan = loanSum;
            goalRecList = goalTypeRec;
            totalGoal = goalSum;
            client = clnt;
            isportalUser = isPortalEnabled;
            totalTransaction =  transactionSum;
            transAmount = transactionAmount;
            transAmountExpense = transactionAmountExpense;
            transAmountLoan = transactionAmountLoan;
            sumOfIncome = sumOfIncomes;
            sumOfExpense = sumOfExpenses ; 
            sumOfLoan = sumOfLoans ; 
            TransSumValInc = transInc ;
            TransSumValExp =  transExp ;
            TransSumValLoan = transLoan ;
        }
        
    }
    
    @AuraEnabled
    public static wrapIncome getBudget(String clientId ){
        System.debug(clientId);
        Double sum = 0 ; 
        Boolean isportalEnabled = false;
        Double sumExpense = 0;
        Double sumLoan = 0;
        Double sumGoal = 0;
        Double sumTransaction = 0;
        Double sumTransactionLoan = 0;
        Double  singleTransIncome = 0;
        String num ;
        String expenseSum;
        String loanSum ; 
        String goalSum ;
        wrapIncome wrapobj;
        Date stdate = date.newInstance(date.today().year(), date.today().month(), 1);
        Date enddate = date.newInstance(date.today().year(), date.today().month(), date.daysInMonth(date.today().year(), date.today().month()));     
        Account acc  = new Account();
        Budget__c bg = new Budget__c();
        
        User us = [select contactid , accountid from user where id=: userinfo.getuserid()];
        System.debug('client id =init'+us.contactid +'and account'+us.accountid);
        try{
            if(us.contactid == null){
                if(clientId == 'init') {
                    System.debug('client id =init');
                    acc  = [select id,name,recordtype.developername from account where ownerid =: UserInfo.getUserId() order by name  limit 1 ];
                     System.debug('client id =init'+acc.id);
                }       
                else {
                    acc = [Select id,name ,recordtype.developername from account where id=: clientId];
                } 
            }
            else
            {
                isportalEnabled = true;
                acc = [select id,name,recordtype.developername from account where id=: us.accountid];
            }
            
            List<Budget__c> budgetList= new List<Budget__c>();
            List<Budget__c> IncomeRecord= new List<Budget__c>();
            List<Budget__c> expenseRecord= new List<Budget__c>();
            List<FinServ__FinancialAccount__c> loanRecord = new List<FinServ__FinancialAccount__c>();
            List<FinServ__FinancialGoal__c> goalRecord = new List<FinServ__FinancialGoal__c>();
            List<FinServ__FinancialAccountTransaction__c> transactionRecord = new List<FinServ__FinancialAccountTransaction__c>();
            if(acc.recordtype.developername.equals('IndustriesHousehold'))
            {
                
                budgetList=[select id,Primary_Owner__c,Primary_Owner__r.name,Name,Frequency__c,recordTypeId,recordtype.developername,Yearly_growth__c,End_Date__c,Amount__c,Start_Date__c,Tax_Rate__c,Month__c ,Priority__c,
                            (Select id , FinServ__TransactionDate__c ,Destination_Financial_Account__r.name, FinServ__Amount__c, 
                             Budget_Category__r.Amount__c
                             from Financial_Account_Transactions__r
                             where FinServ__TransactionDate__c = THIS_MONTH)
                            from Budget__c
                            where (((Start_Date__c <=: stdate ) or(Start_Date__c >=: stdate and  Start_Date__c <=: enddate)) and ((End_Date__c >=: stdate) or End_Date__c = null)) and HouseHold__c =:acc.id];
                System.debug('budget list '+budgetList);
                
                loanRecord = [select id ,FinServ__PrimaryOwner__c,FinServ__PrimaryOwner__r.name, Name, APR__c, FinServ__PaymentAmount__c, FinServ__LoanAmount__c, FinServ__PaymentFrequency__c,CreatedDate,FinServ__LoanEndDate__c ,
                              (Select id ,name ,  FinServ__TransactionDate__c ,Destination_Financial_Account__r.name, FinServ__Amount__c ,	FinServ__FinancialAccount__r.FinServ__PaymentAmount__c
                               from Financial_Account_Transactions__r
                               where FinServ__TransactionDate__c = THIS_MONTH)
                              from FinServ__FinancialAccount__c 
                              where RecordType.developername= 'LoanAccount' and  ((( CreatedDate <=: stdate ) or(CreatedDate >=: stdate and  CreatedDate <=: enddate)) and ((FinServ__LoanEndDate__c >=: stdate) or FinServ__LoanEndDate__c = null)) and FinServ__Household__c=:acc.id];
                System.debug('loanRecord '+loanRecord);
                goalRecord = [Select id,FinServ__PrimaryOwner__c ,FinServ__PrimaryOwner__r.name, Name, Start_Value__c , Required_Monthly_Saving__c ,Associated_Account__c,Start_Date__c,FinServ__TargetDate__c 
                              from FinServ__FinancialGoal__c 
                              where ((( Start_Date__c <=: stdate ) or(Start_Date__c >=: stdate and  Start_Date__c <=: enddate)) and ((FinServ__TargetDate__c >=: stdate) or FinServ__TargetDate__c = null)) and FinServ__Household__c=:acc.id and RecordType.DeveloperName != 'Scenario_Record_Type'];
            } 
            else
            {
                System.debug('aa');
                budgetList=[select id,Primary_Owner__c,Name,Frequency__c,Primary_Owner__r.name,recordTypeId,recordtype.developername,Yearly_growth__c,End_Date__c,Amount__c,Start_Date__c,Tax_Rate__c,Month__c ,Priority__c,
                            (Select id , FinServ__TransactionDate__c ,Destination_Financial_Account__r.name, FinServ__Amount__c, 
                             Budget_Category__r.Amount__c
                             from Financial_Account_Transactions__r
                             where FinServ__TransactionDate__c = THIS_MONTH) 
                            from Budget__c
                            where (((Start_Date__c <=: stdate ) or(Start_Date__c >=: stdate and 
                                                                          Start_Date__c <=: enddate)) and ((End_Date__c >=: stdate) or End_Date__c = null)) and 
                            Primary_Owner__c =:acc.id];
                loanRecord = [select id ,FinServ__PrimaryOwner__c, Name, FinServ__PrimaryOwner__r.name,APR__c, FinServ__PaymentAmount__c, FinServ__LoanAmount__c, FinServ__PaymentFrequency__c,CreatedDate,FinServ__LoanEndDate__c,              
                              (Select id ,name ,  FinServ__TransactionDate__c ,Destination_Financial_Account__r.name, FinServ__Amount__c ,	FinServ__FinancialAccount__r.FinServ__PaymentAmount__c
                               from Financial_Account_Transactions__r
                               where FinServ__TransactionDate__c = THIS_MONTH)
                              from FinServ__FinancialAccount__c 
                              where RecordType.developername= 'LoanAccount' and  ((( CreatedDate <=: stdate ) or(CreatedDate >=: stdate and  CreatedDate <=: enddate)) and ((FinServ__LoanEndDate__c >=: stdate) or FinServ__LoanEndDate__c = null)) and FinServ__PrimaryOwner__c =:acc.id];
                System.debug('loan list '+loanRecord);
                goalRecord = [Select id,FinServ__PrimaryOwner__c , Name, FinServ__PrimaryOwner__r.name,Start_Value__c , Required_Monthly_Saving__c ,Associated_Account__c,Start_Date__c,FinServ__TargetDate__c from FinServ__FinancialGoal__c where ((( Start_Date__c <=: stdate ) or(Start_Date__c >=: stdate and  Start_Date__c <=: enddate)) and ((FinServ__TargetDate__c >=: stdate) or FinServ__TargetDate__c = null)) and FinServ__PrimaryOwner__c =:acc.id and RecordType.DeveloperName != 'Scenario_Record_Type'];
                
                
            }     
            for(Budget__c getRecords : budgetList){
                If( getRecords.recordtype.developername == 'Income_Record_Type' ){ 
                    IncomeRecord.add(getRecords);                
                }
                else if (getRecords.recordtype.developername == 'Expense_Record_Type' )
                {
                    expenseRecord.add(getRecords);                
                }            
            }            
            for ( Budget__c tIncome  : IncomeRecord){
                if (tIncome.Frequency__c=='Monthly'){
                    sum = sum + tIncome.Amount__c ; 
                    
                }  
                else if (tIncome.Frequency__c=='Semi Monthly'){
                    sum = sum + (tIncome.Amount__c *2) ; 
                    
                }
                else if(tIncome.Frequency__c=='Bi-Weekly'){
                    sum = sum + (tIncome.Amount__c *2.16) ; 
                }
                else if(tIncome.Frequency__c=='Weekly'){
                    sum = sum + (tIncome.Amount__c *4.33) ; 
                    
                }
                num = '$' + sum.format();
            }
            for ( Budget__c tExpense  : expenseRecord){
                sumExpense = sumExpense + tExpense.Amount__c ;  
                expenseSum ='$' + sumExpense.format();
            }
            for ( FinServ__FinancialAccount__c tLoan  : loanRecord){
                if (tLoan.FinServ__PaymentFrequency__c=='Monthly'){
                    sumLoan = sumLoan + tLoan.FinServ__PaymentAmount__c ;  
                    
                }  
                else if (tLoan.FinServ__PaymentFrequency__c=='Semi Monthly'){
                    sumLoan = sumLoan + (tLoan.FinServ__PaymentAmount__c*2) ;  
                    
                }
                else if(tLoan.FinServ__PaymentFrequency__c=='Biweekly'){
                    sumLoan = sumLoan + (tLoan.FinServ__PaymentAmount__c*2.16) ;  
                }
                else if(tLoan.FinServ__PaymentFrequency__c=='Weekly'){
                    sumLoan = sumLoan + (tLoan.FinServ__PaymentAmount__c*4.33) ;  
                    
                }
                loanSum = '$' + sumLoan.format();
            }
            for (FinServ__FinancialGoal__c tGoal  : goalRecord){
                sumGoal = sumGoal + tGoal.Required_Monthly_Saving__c ; 
                goalSum = '$' + sumGoal.format();
            }
            System.debug('aaaaa');
            Double valTrans = 0 ;
            Map<Id ,Double> getTransactionAmount = new Map<Id, Double>();
            Map<Id ,String> getTransactionAmountIncome = new Map<Id, String>();
            for(Budget__c tAmount : IncomeRecord){
                Double percentage = 0;
                Double transactionAmount=0;
                for(FinServ__FinancialAccountTransaction__c tTransaction : tAmount.Financial_Account_Transactions__r ){                
                    percentage = percentage + tTransaction.FinServ__Amount__c ; 
                    transactionAmount=tTransaction.Budget_Category__r.Amount__c;
                    
                    //sumTransaction = ((percentage / tTransaction.Budget_Category__r.Amount__c) * 100);
                    //getTransactionAmount.put(tAmount.id, sumTransaction);
                    valTrans = valTrans + tTransaction.FinServ__Amount__c ;   
                }
                
                if (tAmount.Frequency__c=='Monthly' && transactionAmount!=0){
                    sumTransaction = ((percentage / transactionAmount) * 100);
                    getTransactionAmount.put(tAmount.id, sumTransaction);
                    System.debug(sumTransaction);
                }  
                else if (tAmount.Frequency__c=='Semi Monthly'&& transactionAmount!=0){
                    sumTransaction = ((percentage / (transactionAmount*2)) * 100);
                    getTransactionAmount.put(tAmount.id, sumTransaction);
                    System.debug(sumTransaction);
                    
                }
                else if(tAmount.Frequency__c=='Bi-Weekly'&& transactionAmount!=0){
                    sumTransaction = ((percentage / (transactionAmount*2.16)) * 100);
                    getTransactionAmount.put(tAmount.id, sumTransaction); 
                    System.debug(sumTransaction);
                    
                }
                else if(tAmount.Frequency__c=='Weekly'&& transactionAmount!=0){
                    sumTransaction = ((percentage /(transactionAmount*4.33)) * 100);
                    getTransactionAmount.put(tAmount.id, sumTransaction);
                    System.debug(sumTransaction);
                    
                    
                }
                getTransactionAmountIncome.put(tAmount.id, percentage.format());  
            }
            String vInc =  valTrans.format();
            Double valTransExp = 0 ;
            Map<Id ,Double> getTransactionAmountExpense = new Map<Id, Double>();
            Map<Id ,String> getTransactionAmountTotalExpense = new Map<Id, String>();
            for(Budget__c tAmount : expenseRecord){
                Double percentage = 0;
                for(FinServ__FinancialAccountTransaction__c tTransaction : tAmount.Financial_Account_Transactions__r ){                
                    percentage = percentage + tTransaction.FinServ__Amount__c ;
                    sumTransaction = ((percentage / tTransaction.Budget_Category__r.Amount__c) * 100);
                    getTransactionAmountExpense.put(tAmount.id, sumTransaction);
                    valTransExp = valTransExp + tTransaction.FinServ__Amount__c ;   
                }
                getTransactionAmountTotalExpense.put(tAmount.id, percentage.format());
                //System.debug('the percentage id for expense :'+ sumTransaction);
                System.debug('the map key and value for expense are:'+ getTransactionAmountTotalExpense );
            }
            String vExp =  valTransExp.format();
            Double valTransLoan = 0 ;
            Map<Id ,Double> getTransactionAmountLoan = new Map<Id, Double>();
            Map<Id ,String> getTransactionAmountTotalLoan = new Map<Id, String>();
            for(FinServ__FinancialAccount__c tAmount : loanRecord){
                System.debug('loan record');
                Double percentage = 0;
                Double sumLoanTransaction=0;
                System.debug('loan record Id'+tAmount.Id);
                System.debug(tAmount.Financial_Account_Transactions__r);
                for(FinServ__FinancialAccountTransaction__c tTransaction : tAmount.Financial_Account_Transactions__r ){
                    percentage = percentage + tTransaction.FinServ__Amount__c ;
                    sumLoanTransaction=tTransaction.FinServ__FinancialAccount__r.FinServ__PaymentAmount__c;
                    System.debug(percentage);
                    //sumTransactionLoan = ((percentage / tTransaction.FinServ__FinancialAccount__r.FinServ__PaymentAmount__c) * 100);
                    //getTransactionAmountLoan.put(tAmount.id, sumTransactionLoan);
                    
                    valTransLoan = valTransLoan + tTransaction.FinServ__Amount__c ;   
                }
                if (tAmount.FinServ__PaymentFrequency__c=='Monthly' && sumLoanTransaction!=0){
                    sumTransaction = ((percentage / sumLoanTransaction) * 100);
                    getTransactionAmountLoan.put(tAmount.id, sumTransaction);
                    System.debug(sumTransaction);
                }  
                else if (tAmount.FinServ__PaymentFrequency__c=='Semi Monthly'&& sumLoanTransaction!=0){
                    sumTransaction = ((percentage / (sumLoanTransaction*2)) * 100);
                    getTransactionAmountLoan.put(tAmount.id, sumTransaction);
                    System.debug(sumTransaction);
                    
                }
                else if(tAmount.FinServ__PaymentFrequency__c=='Biweekly'&& sumLoanTransaction!=0){
                    sumTransaction = ((percentage / (sumLoanTransaction*2.16)) * 100);
                    getTransactionAmountLoan.put(tAmount.id, sumTransaction); 
                    System.debug(sumTransaction);
                    
                }
                else if(tAmount.FinServ__PaymentFrequency__c=='Weekly'&& sumLoanTransaction!=0){
                    sumTransaction = ((percentage /(sumLoanTransaction*4.33)) * 100);
                    getTransactionAmountLoan.put(tAmount.id, sumTransaction);
                    System.debug(sumTransaction);
                    
                    
                }
                getTransactionAmountTotalLoan.put(tAmount.id, percentage.format());
                //  System.debug('the percentage id for loan is :'+ sumTransactionLoan);
                System.debug('the map key and value for loan are:'+ getTransactionAmountTotalLoan );
            }
            String vLoan =  valTransLoan.format();
            System.debug('aaaa');
            wrapobj= new wrapIncome(IncomeRecord,num,expenseRecord ,expenseSum ,goalRecord, goalSum , loanRecord , loanSum, acc,isportalEnabled ,
                                    sumTransaction , getTransactionAmount ,getTransactionAmountExpense,getTransactionAmountLoan,
                                    getTransactionAmountIncome,getTransactionAmountTotalExpense,getTransactionAmountTotalLoan,
                                    vInc , vExp , vLoan);  
                    System.debug('1'+wrapobj);

        }
        catch(Exception e){
            System.debug(e.getStackTraceString());
            FinacastUtility.ExceptionHandle(e.getLineNumber(), e.getMessage(), e.getStackTraceString());
        }
        System.debug('2'+wrapobj);
        return wrapobj;
        
    }
    
}