src/objects/Budget__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount after tax per pay check ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Semi Monthly</fullName>
                </value>
                <value>
                    <fullName>Bi-Weekly</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Owner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budgets (Account)</relationshipLabel>
        <relationshipName>Budgets1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <recordTypes>
        <fullName>Expense_Record_Type</fullName>
        <active>true</active>
        <label>Expense Record Type</label>
    </recordTypes>
    <recordTypes>
        <fullName>Income_Record_Type</fullName>
        <active>true</active>
        <label>Income Record Type</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>FinServ__APY__c</fullName>
        <inlineHelpText>Kindly fill the Annual Yield Rate for this Financial Account. Do not leave this blank.</inlineHelpText>
        <label>APY</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>FinServ__Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__PaymentFrequency__c</fullName>
        <label>Payment Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Biweekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quaterly</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                    <isActive>false</isActive>
                    <label>Annual</label>
                </value>
                <value>
                    <fullName>Semiannual</fullName>
                    <isActive>false</isActive>
                    <label>Semiannual</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialAccountTransaction__c.object
<CustomObject>
    <description>Represents information about financial account transactions.</description>
    <fields>
        <fullName>Budget_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Category</label>
        <referenceTo>Budget__c</referenceTo>
        <relationshipLabel>Financial Account Transactions</relationshipLabel>
        <relationshipName>Financial_Account_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__Amount__c</fullName>
        <description>The amount of each transaction. This field is used for reconciliation.</description>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__FinancialAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account</label>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Account Transactions</relationshipLabel>
        <relationshipName>FinancialAccountTranslations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__TransactionDate__c</fullName>
        <description>The date each transaction occurred. This field is used for reconciliation.</description>
        <label>Transaction Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Financial Account Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialGoal__c.object
<CustomObject>
    <description>Tracks a client&apos;s goal.</description>
    <fields>
        <fullName>Associated_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Associated Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3 AND 4</booleanFilter>
            <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Scenario_Credit_Cards_Record_Type</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Scenario_Loans_Record_Type</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>LoanAccount</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>CreditCard</value>
            </filterItems>
            <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Goals</relationshipLabel>
        <relationshipName>Financial_Goals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>IndustriesIndividual</value>
            </filterItems>
            <filterItems>
                <field>Account.FinServ__IndividualType__c</field>
                <operation>equals</operation>
                <value>Individual</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Financial Goals</relationshipLabel>
        <relationshipName>ClientFinancialGoals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__TargetDate__c</fullName>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Goal_Priority__c</fullName>
        <label>Goal Priority</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Priority 1 (must have)</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Priority 2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Priority 3</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Required_Monthly_Saving__c</fullName>
        <label>Required Monthly Saving</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Value__c</fullName>
        <label>Start Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Goal</label>
    <nameField>
        <label>Financial Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AddIncomeControllerTest.cls
//---------------------Test class for AddIncomeController -------------------------------------------------------//

@isTest
public class AddIncomeControllerTest {
    
    @isTest
    public static void AddIncomeapex(){
        String namespace= NamespaceUtility.returnNamespace();
        
        Account acc1 = new Account();
        acc1.Name= 'Test Account1';  
        acc1.OwnerId = UserInfo.getUserId();
        Account acc2 = new Account();
        acc2.Name = 'Test Account2';
        
        
        list<RecordType> rcc1 =[Select Id From RecordType Where SobjectType='Account' And Name='Individual' limit 1];
        if(rcc1.size()>0){
            acc1.RecordTypeId = rcc1[0].Id;          
        }
        insert acc1;       
        
        list<RecordType> recType =[Select Id From RecordType Where SobjectType='Account' And Name='IndustriesHousehold' limit 1];
        if(recType.size()>0){
            acc2.RecordTypeId = recType[0].Id;           
        }
        insert acc2;
        
        FinServ__FinancialAccount__c financial1 = new FinServ__FinancialAccount__c();
        financial1.Name = 'Test Financial Account 1';
        list<RecordType> rcc =[Select Id From RecordType Where SobjectType='FinServ__FinancialAccount__c' And Name='Loan Account' limit 1];
        financial1.RecordtypeId = rcc[0].Id;
        financial1.FinServ__Balance__c = 5000;
        financial1.FinServ__PrimaryOwner__c= acc1.Id;
        financial1.FinServ__APY__c = 4;
        financial1.FinServ__PaymentFrequency__c='Monthly';
        insert financial1;

        financial1 = new FinServ__FinancialAccount__c();
        financial1.Name = 'Test Financial Account 1';
        rcc =[Select Id From RecordType Where SobjectType='FinServ__FinancialAccount__c' And Name='Loan Account' limit 1];
        financial1.RecordtypeId = rcc[0].Id;
        financial1.FinServ__Balance__c = 5000;
        financial1.FinServ__PrimaryOwner__c= acc1.Id;
        financial1.FinServ__APY__c = 4;
        financial1.FinServ__PaymentFrequency__c='Semi Monthly';
        insert financial1;  
        
        financial1 = new FinServ__FinancialAccount__c();
        financial1.Name = 'Test Financial Account 1';
        rcc =[Select Id From RecordType Where SobjectType='FinServ__FinancialAccount__c' And Name='Loan Account' limit 1];
        financial1.RecordtypeId = rcc[0].Id;
        financial1.FinServ__Balance__c = 5000;
        financial1.FinServ__PrimaryOwner__c= acc1.Id;
        financial1.FinServ__APY__c = 4;
        financial1.FinServ__PaymentFrequency__c='Biweekly';
        insert financial1; 
        
		 financial1 = new FinServ__FinancialAccount__c();
        financial1.Name = 'Test Financial Account 1';
        rcc =[Select Id From RecordType Where SobjectType='FinServ__FinancialAccount__c' And Name='Loan Account' limit 1];
        financial1.RecordtypeId = rcc[0].Id;
        financial1.FinServ__Balance__c = 5000;
        financial1.FinServ__PrimaryOwner__c= acc1.Id;
        financial1.FinServ__APY__c = 4;
        financial1.FinServ__PaymentFrequency__c='Weekly';
        insert financial1; 
        
       
        String sObject1=namespace+'Budget__c';
        //String sObject2=namespace+'Income_Record_Type';
        Budget__c bg = new Budget__c();
        bg.name = 'Test';
        list<RecordType> rcc2 =[Select Id From RecordType Where SobjectType=:sObject1 And DeveloperName ='Income_Record_Type' limit 1];
        bg.RecordtypeId = rcc2[0].Id;
        bg.Start_Date__c = date.newInstance(2019, 1, 1);
        bg.End_Date__c = date.newInstance(2019, 31, 1);
        bg.Amount__c = 1000;
        bg.Primary_Owner__c= acc1.Id;
        bg.Frequency__c='Monthly';
        insert bg;
        
        bg = new Budget__c();
        bg.name = 'Test';
        rcc2 =[Select Id From RecordType Where SobjectType=:sObject1  And DeveloperName ='Income_Record_Type' limit 1];
        bg.RecordtypeId = rcc2[0].Id;
        bg.Start_Date__c = date.newInstance(2019, 1, 1);
        bg.End_Date__c = date.newInstance(2019, 31, 1);
        bg.Amount__c = 1000;
        bg.Primary_Owner__c= acc1.Id;
        bg.Frequency__c='Semi Monthly';
        insert bg;
        bg = new Budget__c();
        bg.name = 'Test';
        rcc2 =[Select Id From RecordType Where SobjectType=:sObject1 And DeveloperName ='Income_Record_Type' limit 1];
        bg.RecordtypeId = rcc2[0].Id;
        bg.Start_Date__c = date.newInstance(2019, 1, 1);
        bg.End_Date__c = date.newInstance(2019, 31, 1);
        bg.Amount__c = 1000;
        bg.Primary_Owner__c= acc1.Id;
        bg.Frequency__c='Bi-Weekly';
        insert bg;

        
        
        String sObject3=namespace+'Expense_Record_Type';
        Budget__c bg1 = new Budget__c();
        bg1.name = 'Test1';
        list<RecordType> rcc3 =[Select Id From RecordType Where SobjectType=:sObject1 And DeveloperName ='Expense_Record_Type' limit 1];
        bg1.RecordtypeId = rcc3[0].Id;
        bg1.Start_Date__c = date.newInstance(2019, 1, 1);
        bg1.End_Date__c = date.newInstance(2019, 31, 1);
        bg1.Amount__c = 1000;
        bg1.Primary_Owner__c= acc1.Id;
        insert bg1;
        
         FinServ__FinancialAccountTransaction__c transaction1 = new FinServ__FinancialAccountTransaction__c();
        //transaction1.Name = 'Test transcation Account 1';
        //list<RecordType> rcc =[Select Id From RecordType Where SobjectType='FinServ__FinancialAccount__c' And Name='Loan Account' limit 1];
        //financial1.RecordtypeId = rcc[0].Id;
        transaction1.FinServ__TransactionDate__c = date.newInstance(2019, 1, 1);
        transaction1.OwnerId= acc1.OwnerId;
        transaction1.Budget_Category__c=bg1.id;
        transaction1.FinServ__Amount__c = 4000;
        insert transaction1;
        
        FinServ__FinancialAccount__c fa = new FinServ__FinancialAccount__c(Name='SahilTest',FinServ__PrimaryOwner__c=acc1.Id);
        insert fa;
        FinServ__FinancialGoal__c goal1 = new FinServ__FinancialGoal__c();
        goal1.Name = 'test goal 1';
        goal1.Required_Monthly_Saving__c = 5000;
        goal1.Start_Date__c = date.today();
        goal1.Start_Value__c = 456700;
        goal1.FinServ__TargetDate__c = date.today()+90;
        goal1.FinServ__PrimaryOwner__c=acc1.Id;
        goal1.Required_Monthly_Saving__c = 4500;
        goal1.Goal_Priority__c='Priority 2';
        goal1.Associated_Account__c=fa.Id;
        insert goal1;
        
        
        // ----- Test Class ---------------------------------------------//  
        bg = [select id ,Primary_Owner__c,Amount__c from Budget__C where name = 'Test' limit 1];
        FinServ__FinancialAccount__c fAcc1 = [select id  from FinServ__FinancialAccount__c where name = 'Test Financial Account 1' limit 1];
        FinServ__FinancialGoal__c fGoal1 = [select FinServ__TargetDate__c,Start_Value__c,Required_Monthly_Saving__c ,FinServ__PrimaryOwner__c  from FinServ__FinancialGoal__c where name = 'test goal 1' ];
        FinServ__FinancialAccountTransaction__c ftrans1 = [Select id, FinServ__Amount__c from FinServ__FinancialAccountTransaction__c where FinServ__Amount__c = 4000];
        DateTime d = fGoal1.FinServ__TargetDate__c;
        String targetDate = d.format('YYYY-MM-dd');
        //String targetAmt = String.valueOf(fGoal1.Required_Monthly_Saving__c);
        String currentAmount  = String.valueOf(fGoal1.Start_Value__c);       
        AddIncomeController.getRecordType('Income_Record_Type');
        AddIncomeController.getLoanRecordType('LoanAccount');       
        AddIncomeController.getRecordTypeIdbyName('FinServ__FinancialGoal__c' , fGoal1.id);
        AddIncomeController.getRecordIdRecType('Account' , acc1.id);
        AddIncomeController.getTransaction(bg.Id);
        AddIncomeController.getLoanTransaction(fAcc1.id);
        AddIncomeController.getSummaryTransaction(bg.Id);
        AddIncomeController.getLoanSummaryTransaction(fAcc1.id);
        AddIncomeController.wrapIncome result = AddIncomeController.getBudget(acc1.Id);
        AddIncomeController.wrapIncome res = AddIncomeController.getBudget(acc2.Id);
        AddIncomeController.wrapIncome result1 = AddIncomeController.getBudget('init');
        AddIncomeController.wrapIncome result2 = AddIncomeController.getmonthincome('JAN,2019', acc1 );
        AddIncomeController.getMonth('JAN,2019'); 
        AddIncomeController.deleteIncome(bg.id);
        AddIncomeController.deleteGoals(fGoal1.id);
        AddIncomeController.deleteLoan(fAcc1.id);
        AddIncomeController.deleteTransaction(ftrans1.id);
        // GoalsApexController.getGoals();
        /*List<Budget__c> bd = [select id from Budget__c];
Set<Id> bdId = new Set<Id>();
for(Budget__c b : bd) {
bdId.add(b.Id);
}
FinacastBudgetHelper.shareBudget(bdId);*/
        SummaryCashFlowController.getMonth('JAN');
        System.assertEquals('1', '1');
    }
    
}