src/objects/Client_Adviser_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Client_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Adviser Configurations</relationshipLabel>
        <relationshipName>Client_Adviser_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Adviser Configuration</label>
    <nameField>
        <displayFormat>CAC - {0}</displayFormat>
        <label>Client Advisor Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Adviser Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>FinServ__APY__c</fullName>
        <inlineHelpText>Kindly fill the Annual Yield Rate for this Financial Account. Do not leave this blank.</inlineHelpText>
        <label>APY</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>FinServ__Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialGoal__c.object
<CustomObject>
    <description>Tracks a client&apos;s goal.</description>
    <fields>
        <fullName>Associated_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Associated Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3 AND 4</booleanFilter>
            <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Scenario_Credit_Cards_Record_Type</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Scenario_Loans_Record_Type</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>LoanAccount</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>CreditCard</value>
            </filterItems>
            <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Goals</relationshipLabel>
        <relationshipName>Financial_Goals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Goal_Amount__c</fullName>
        <label>Current Goal Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>IndustriesIndividual</value>
            </filterItems>
            <filterItems>
                <field>Account.FinServ__IndividualType__c</field>
                <operation>equals</operation>
                <value>Individual</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Financial Goals</relationshipLabel>
        <relationshipName>ClientFinancialGoals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__TargetDate__c</fullName>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Goal_Priority__c</fullName>
        <label>Goal Priority</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Priority 1 (must have)</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Priority 2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Priority 3</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Required_Monthly_Saving__c</fullName>
        <label>Required Monthly Saving</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Value__c</fullName>
        <label>Start Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Goal</label>
    <nameField>
        <label>Financial Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/GoalsApexController_Test.cls
@isTest(seeAlldata=True)
public class GoalsApexController_Test {
    @isTest
    public static void AddGoalsapex(){
        
        Account acc1 = new Account();
        acc1.Name= 'Test Account1';  
        acc1.OwnerId = UserInfo.getUserId();
        
        list<RecordType> rcc1 =[Select Id From RecordType Where SobjectType='Account' And Name='Individual' limit 1];
        if(rcc1.size()>0){
            acc1.RecordTypeId = rcc1[0].Id;
        }
        insert acc1;       
        
        
        FinServ__FinancialAccount__c financial1 = new FinServ__FinancialAccount__c();
        financial1.Name = 'Test Financial Account 1';
        //list<RecordType> rcc =[Select Id From RecordType Where SobjectType='FinServ__FinancialAccount__c' And Name='Loan Account' limit 1];
        //financial1.RecordtypeId = rcc[0].Id;
        financial1.FinServ__Balance__c = 4596;
        financial1.FinServ__PrimaryOwner__c= acc1.Id;
        financial1.FinServ__APY__c = 4;
        insert financial1;
        
        
        list<FinServ__FinancialGoal__c> Flist = new list<FinServ__FinancialGoal__c>();
        FinServ__FinancialGoal__c goal1 = new FinServ__FinancialGoal__c();
        goal1.Name = 'test goal 1';
        goal1.Required_Monthly_Saving__c = 5000;
        goal1.Associated_Account__c =financial1.id;
        goal1.Current_Goal_Amount__c = financial1.FinServ__Balance__c;
        goal1.Start_Date__c = System.today();
        goal1.Start_Value__c = 456;
        //goal1.Goal_Priority__c = 'Priority 2';
     
        goal1.FinServ__TargetDate__c = System.today()+90;
        goal1.FinServ__PrimaryOwner__c=acc1.Id;
        goal1.Goal_Priority__c = 'Priority 2';
        Flist.add(goal1);
        insert goal1;
        
        Client_Adviser_Configuration__c cAdvisor = new Client_Adviser_Configuration__c();
        cAdvisor.Client_Id__c = acc1.id ;
        insert cAdvisor ;
        
        
        
        
        //FinServ__FinancialAccount__c fAcc1 = [select id  from FinServ__FinancialAccount__c where name = 'Test Financial Account 1'];
        FinServ__FinancialGoal__c fGoal1 = [select id, FinServ__TargetDate__c,Start_Value__c,Required_Monthly_Saving__c ,FinServ__PrimaryOwner__c  from FinServ__FinancialGoal__c where name = 'test goal 1' ];
        GoalsApexController.deleteGoals(goal1.id);
        GoalsApexController.getClientGoals(acc1.id);
        GoalsApexController.getGoals() ;
        GoalsApexController.NumberOfMonths(system.today(), system.today());
        GoalsApexController.curentgoalestimation(500, system.today(), system.today());
        GoalsApexController.goalstatus = 56897;
        GoalsApexController.totalEstimated=555;
        //GoalsApexController.getCurrentAmount(goal1);
                
       
        BankAccountListApexController.getBank();
        BankAccountListApexController.getClientBank(acc1.id);
        BankAccountListApexController.deleteBankAccount(financial1.id);
        BankAccountListApexController.editData(financial1.id, financial1.id, 'facc', '7623872171', 'test', 345, 'abc@mirketa.com');
        
        GoalPerformanceApex.getGoalData(goal1.id);
        // GoalPerformanceApex.WrapperClass result = GoalPerformanceApex.getGoalData(fGoal1.id);
        //GoalsApexController.getGoals();
        // GoalsApexController.getClientGoals(acc1.id);
    } 
}