src/objects/Client_Adviser_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Adviser_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adviser Id</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Client_Adviser_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Adviser Configurations</relationshipLabel>
        <relationshipName>Client_Adviser_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Adviser Configuration</label>
    <nameField>
        <displayFormat>CAC - {0}</displayFormat>
        <label>Client Advisor Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Adviser Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>401K</fullName>
                </value>
                <value>
                    <fullName>529 Account</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>CD</fullName>
                </value>
                <value>
                    <fullName>Checking</fullName>
                </value>
                <value>
                    <fullName>IRA</fullName>
                </value>
                <value>
                    <fullName>Money Market</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Retail Brokerage</fullName>
                </value>
                <value>
                    <fullName>Roth IRA</fullName>
                </value>
                <value>
                    <fullName>Saving</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>Debt</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bank_Phone_Number__c</fullName>
        <label>Bank Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>FinServ__APY__c</fullName>
        <inlineHelpText>Kindly fill the Annual Yield Rate for this Financial Account. Do not leave this blank.</inlineHelpText>
        <label>APY</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>FinServ__CurrentPostedBalance__c</fullName>
        <label>Current Posted Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__PaymentAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BankAccountListApexController.cls
public class BankAccountListApexController {
    @auraEnabled
    public static List<List<Object>> getBank() {
        List<List<Object>> returnObjList = new List<List<Object>>();
      
            List<Client_Adviser_Configuration__c> caConfigList = [select Adviser_Id__c,Client_Id__c,Client_Id__r.name  from Client_Adviser_Configuration__c where adviser_id__c =: UserInfo.getUserId() limit 1];
            Client_Adviser_Configuration__c caConfig = new Client_Adviser_Configuration__c();
            if(caConfigList.size()>0)
            {
                caConfig = caConfigList[0];
            }
            List<FinServ__FinancialAccount__c> retList = [Select id , Name, Account_Type__c,FinServ__PrimaryOwner__r.name, FinServ__CurrentPostedBalance__c, FinServ__APY__c,FinServ__PaymentAmount__c
                                                          from FinServ__FinancialAccount__c where FinServ__PrimaryOwner__c =: caConfig.Client_Id__c ];
            List<String> clientName = new List<String>();
            clientName.add(caConfig.Client_Id__r.name);
            clientName.add(caConfig.Client_Id__c);
            
            returnObjList.add(retList);
            returnObjList.add(clientName);
       
        return  returnObjList;
    }
    
    @auraEnabled
    public static void deleteBankAccount(id accId) {
            if (Schema.sObjectType.FinServ__FinancialAccount__c.isDeletable()){
                FinServ__FinancialAccount__c accItem = [Select id from FinServ__FinancialAccount__c where id =:accId];
                if (Schema.sObjectType.FinServ__FinancialAccount__c.isDeletable()){
                    delete accItem;
                }
            }
        
    }
    
    
    @auraEnabled
    public static List<List<Object>> getClientBank(String clientId) {
        List<List<Object>> returnObjList = new List<List<Object>>();
        
        
            List<FinServ__FinancialAccount__c> retList = [Select id , Name, Account_Type__c,FinServ__PrimaryOwner__r.name, FinServ__CurrentPostedBalance__c, FinServ__APY__c,FinServ__PaymentAmount__c
                                                          from FinServ__FinancialAccount__c where FinServ__PrimaryOwner__c =: clientId ];
            List<String> clientName = new List<String>();
            
            clientName.add([select id,name from account where id=: clientId ].name);
            clientName.add([select id,name from account where id=: clientId ].id);
            
            returnObjList.add(retList);
            returnObjList.add(clientName);
       
        return  returnObjList;
    }
    
    @auraEnabled
    public static void editData( String recId, String owner, String type, String phoneno, String name, Decimal cVal, String website)
    {
        
            List<FinServ__FinancialAccount__c> acc = [Select FinServ__PrimaryOwner__c,Account_Type__c, 
                                                      Bank_Phone_Number__c, Name,FinServ__CurrentPostedBalance__c, Website__c
                                                      from FinServ__FinancialAccount__c where id = :recId];
            System.debug('enter apex');
            System.debug('acc: '+acc);
            for(FinServ__FinancialAccount__c a : acc)
            {a.FinServ__PrimaryOwner__c = owner;
             
             a.Bank_Phone_Number__c = phoneno;
             a.FinServ__CurrentPostedBalance__c = cVal;
             a.Website__c = website;
            }
            System.debug('acc2: '+acc);
            update(acc);
        
    }
    
}