src/objects/Finsol_Custom_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Namespace__c</fullName>
        <label>Namespace</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Finsol Custom Setting</label>
</CustomObject>

src/classes/NamespaceUtility.cls
public class NamespaceUtility {
     public static String returnNamespace(){
      /*  string namespace='';
      List<Finsol_Custom_Setting__c> finsolCustomSetting= [SELECT Namespace__c FROM Finsol_Custom_Setting__c where Name='Finsol' limit 1];
        if(!finsolCustomSetting.isEmpty()){
        if(finsolCustomSetting[0].Namespace__c!=null)
            namespace=finsolCustomSetting[0].Namespace__c+'__';
        }*/
        return '';
    }

}