src/objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>401K</fullName>
                </value>
                <value>
                    <fullName>529 Account</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>CD</fullName>
                </value>
                <value>
                    <fullName>Checking</fullName>
                </value>
                <value>
                    <fullName>IRA</fullName>
                </value>
                <value>
                    <fullName>Money Market</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Retail Brokerage</fullName>
                </value>
                <value>
                    <fullName>Roth IRA</fullName>
                </value>
                <value>
                    <fullName>Saving</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>Debt</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinServ__APY__c</fullName>
        <inlineHelpText>Kindly fill the Annual Yield Rate for this Financial Account. Do not leave this blank.</inlineHelpText>
        <label>APY</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>FinServ__Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialGoal__c.object
<CustomObject>
    <description>Tracks a client&apos;s goal.</description>
    <fields>
        <fullName>Associated_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Associated Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3 AND 4</booleanFilter>
            <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Scenario_Credit_Cards_Record_Type</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Scenario_Loans_Record_Type</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>LoanAccount</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>CreditCard</value>
            </filterItems>
            <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Goals</relationshipLabel>
        <relationshipName>Financial_Goals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>IndustriesIndividual</value>
            </filterItems>
            <filterItems>
                <field>Account.FinServ__IndividualType__c</field>
                <operation>equals</operation>
                <value>Individual</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Financial Goals</relationshipLabel>
        <relationshipName>ClientFinancialGoals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__TargetDate__c</fullName>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FinServ__TargetValue__c</fullName>
        <label>Target Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Goal_Priority__c</fullName>
        <label>Goal Priority</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Priority 1 (must have)</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Priority 2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Priority 3</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Required_Monthly_Saving__c</fullName>
        <label>Required Monthly Saving</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Value__c</fullName>
        <label>Start Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Goal</label>
    <nameField>
        <label>Financial Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Nonretirementgoalapexcontroller.cls
public class Nonretirementgoalapexcontroller {
        public static string namespace{get; set;}

    

    
    @auraEnabled
    public static FinServ__FinancialGoal__c getNonRetirementGoalRecord(String goalsId){
        System.debug('the goals id is:' + goalsId);
        FinServ__FinancialGoal__c allGoals = [select FinServ__PrimaryOwner__c,Name,FinServ__TargetValue__c,FinServ__TargetDate__c,Associated_Account__c,Goal_Priority__c,Required_Monthly_Saving__c,Start_Date__c,Start_Value__c from FinServ__FinancialGoal__c where id= :goalsId];
        
        System.debug('goals are '+allGoals);
        return allGoals ;
    }
    
    @auraEnabled   
    public static List<FinServ__FinancialAccount__c> dample(String clientId){
        System.debug('clientId-sassa-->'+clientId);      
        List<FinServ__FinancialAccount__c> a = [select Id, Name from FinServ__FinancialAccount__c where FinServ__PrimaryOwner__c = :clientId AND (Account_Type__c='401K' OR Account_Type__c='529 Account' OR Account_Type__c='Cash' OR Account_Type__c='CD'
                                                                                                                                                                                                                                     OR Account_Type__c='Checking' OR Account_Type__c='IRA' OR Account_Type__c='Money Market' OR Account_Type__c='Other' OR Account_Type__c='Retail Brokerage' OR Account_Type__c='Roth IRA'  OR Account_Type__c='Savings')];
        return a;
    }
    
    @auraEnabled
    public static Double getCurrentAmount(String goalId,String accId)
    {
        
        Double interestRate = 0;
        Double currAmt = 0;

        system.debug('gaccid'+accId );
        try{
            if(accId != null&& accId !='')
            {
                FinServ__FinancialAccount__c acc = [select FinServ__Balance__c, FinServ__APY__c, id from FinServ__FinancialAccount__c where id = :accId];
                Double bal = acc.FinServ__Balance__c;
                if(acc.FinServ__APY__c != null)
                {
                    interestRate = acc.FinServ__APY__c;
                }
                else 
                    interestRate = 0; 
                
                list<FinServ__FinancialGoal__c> allAssocGoals = [select Associated_Account__c,Required_Monthly_Saving__c, Start_Date__c, Start_Value__c,FinServ__TargetValue__c from FinServ__FinancialGoal__c where Associated_Account__c = :accId and Id!=:goalId];
                
                Double totalEstimated = 0;
                Double remainingAmount = 0;
   			  Decimal growth=Core_GoalUtility.calculateGrowth(interestRate);       
                for(FinServ__FinancialGoal__c relgoal : allAssocGoals )
                {
                    totalEstimated = totalEstimated +  ((Decimal) Core_GoalUtility.curentgoalestimation2((double)(relgoal.Required_Monthly_Saving__c), relgoal.Start_Date__c, date.today(),growth,relgoal.Start_Value__c,relgoal.FinServ__TargetValue__c)).setScale(2, RoundingMode.HALF_UP);                     
                }
                remainingAmount = bal - totalEstimated;
                if(remainingAmount < 0){
                    remainingAmount = 0;
                }
                currAmt = Double.valueOf(remainingAmount);
               /* if(targetDate != null && targetAmt != null){
                    Date tarDate = Date.valueOf(targetDate);
                    Double tarAmt = Double.valueOf(targetAmt);
                    wrapper.emi = Math.round(getMonthlyContri(accId, currAmt, tarDate, tarAmt));
                }
                else{
                    wrapper.emi = 0; 
                }
            }
            else{
                wrapper.currentAmt = null;
            }*/
             if(TEST.isRunningTest())
                throw new NullPointerException();
        }
        }
        catch(Exception e){
            FinacastUtility.ExceptionHandle(e.getLineNumber(), e.getMessage(), e.getStackTraceString());
        }
                return Math.round(currAmt);
        
    }
    
    /* get monthly contribution
* used in  getCurrentAmount
* **/
        @auraEnabled

    public static Double getMonthlyContri(String accId, Double currAmt, Date target, Double tAmt)
    {
        
        Integer months = date.today().monthsBetween(target);
        System.debug('months'+months);
        Double installment = 0;
         //Double temp=1;
        Double interestRate=[Select FinServ__APY__c from FinServ__FinancialAccount__c where Id=:accId LIMIT 1].FinServ__APY__c;
      //  Double growth = ((Math.pow((1 + (interestRate/100)), (temp/12)))- 1);
      Double growth=Core_GoalUtility.calculateGrowth(interestRate);
        try{
            If (tAmt > (currAmt * (Math.pow((1 + growth),months)))){
                If (growth > 0){
                    installment = ((tAmt - currAmt * (Math.pow((1 + growth), months))) * growth) / ((Math.pow((1 + growth), months)) - 1);
                } 
                Else {
                    installment = (tAmt - currAmt) / months;
                }
                
            }
            if(installment < 0){
                installment = 0;
            }
            else{
                installment += 1;
            }
             if(TEST.isRunningTest())
                throw new NullPointerException();
        }
        catch(Exception e){
            FinacastUtility.ExceptionHandle(e.getLineNumber(), e.getMessage(), e.getStackTraceString());
        }
        return Math.round(installment);
    }
    
    
}