src/objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>FinServ__Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialGoal__c.object
<CustomObject>
    <description>Tracks a client&apos;s goal.</description>
    <fields>
        <fullName>Associated_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Associated Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3 AND 4</booleanFilter>
            <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Scenario_Credit_Cards_Record_Type</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Scenario_Loans_Record_Type</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>LoanAccount</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>CreditCard</value>
            </filterItems>
            <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Goals</relationshipLabel>
        <relationshipName>Financial_Goals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>IndustriesIndividual</value>
            </filterItems>
            <filterItems>
                <field>Account.FinServ__IndividualType__c</field>
                <operation>equals</operation>
                <value>Individual</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Financial Goals</relationshipLabel>
        <relationshipName>ClientFinancialGoals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Required_Monthly_Saving__c</fullName>
        <label>Required Monthly Saving</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Value__c</fullName>
        <label>Start Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Goal</label>
    <nameField>
        <label>Financial Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestRetirementGoalApexController.cls
@isTest
public class TestRetirementGoalApexController {
    @testSetup
    static void testData()
    {
        Account acc = new Account();
        acc.Name = 'test account';
        
        
        String accRecType =Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        acc.RecordTypeId = accRecType;
        
        insert acc; 
        
        Account aId = [Select id from Account where name = 'test account'];
        FinServ__FinancialAccount__c fAcc = new FinServ__FinancialAccount__c();
        fAcc.Name = 'test financial account';
        fAcc.FinServ__PrimaryOwner__c = aId.Id;
        fAcc.FinServ__Balance__c = 500;
        RecordType rType = [select id from RecordType where name = 'Bank Account'];
        fAcc.RecordTypeId = rType.id;
        insert fAcc;
        
        FinServ__FinancialGoal__c goal = new FinServ__FinancialGoal__c();
        goal.Name = 'test goal';
        goal.Associated_Account__c = fAcc.Id;
        goal.FinServ__PrimaryOwner__c = acc.id;
        goal.Required_Monthly_Saving__c = 5000;
        goal.Start_Date__c = date.today();
        goal.Start_Value__c = 500;
        insert goal;
    }
    
    static testMethod void testRetirementApex()
    {
        
        Account accId = [select id from Account where name = 'test account'];
        RetirementGoalApexController.getDate(accId.id);
        FinServ__FinancialAccount__c fAccId = [select id from FinServ__FinancialAccount__c where name = 'test financial account'];
        Date retire = date.today()+900;
        String retireDate = String.valueOf(retire);
        
        //RetirementGoalApexController.getCurrentAmount( '500', '10', '100', '100000', retireDate);
        
        DateTime target = Date.today()+900;
        String tDate = target.format('YYYY-MM-dd');
        System.debug('target: '+target);
        System.debug('tDate: '+tDate);
        
        FinServ__FinancialGoal__c fGoal = [select Associated_Account__c, Start_Value__c from FinServ__FinancialGoal__c where name = 'test goal' ];
        DateTime birth = date.today();
        String birthDate = birth.format('YYYY-MM-dd');
        String current = String.valueOf(fGoal.Start_Value__c);
        
        test.startTest();
        RetirementGoalApexController.getAmountMonth(500, 3, 6,'10','60', birthDate);
        RetirementGoalApexController.getAmountMonth(500, 0, 0,'10','60', birthDate);  
        RetirementGoalApexController.getAmountMonth(500, 3, 3,'10','60', birthDate);
        RetirementGoalApexController.getAmtAndContri(fAccId.id, '10','3', '100000', tDate,current);
        RetirementGoalApexController.getAmtAndContri(fAccId.id, '10','3', '100000', tDate,null);        
       
        RetirementGoalApexController.saveData(String.valueOf((accId.id)),'test save goal', String.valueOf(date.today()), '30','3', '60' , '500','6', '5200',String.valueOf(fGoal.Associated_Account__c) , '1', '500', tDate, '300');
        // RetirementGoalApexController.getGoalData(fAccId.id);
        test.stopTest();
        System.assertEquals('1','1');
    }
    
}