src/objects/FinServ__FinancialAccountTransaction__c.object
<CustomObject>
    <description>Represents information about financial account transactions.</description>
    <fields>
        <fullName>FinServ__Amount__c</fullName>
        <description>The amount of each transaction. This field is used for reconciliation.</description>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__TransactionDate__c</fullName>
        <description>The date each transaction occurred. This field is used for reconciliation.</description>
        <label>Transaction Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FinServ__TransactionType__c</fullName>
        <description>Type of the transaction. This field is used to determine whether the transaction falls under income or expense. Also used in reconciliation logic.</description>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Debit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Financial Account Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TransactionGraphsApexControllerTest.cls
@isTest
public class TransactionGraphsApexControllerTest {
    @isTest public static void testTransaction(){
        FinServ__FinancialAccountTransaction__c trans = new FinServ__FinancialAccountTransaction__c();
        trans.FinServ__TransactionDate__c = Date.today();
        trans.FinServ__Amount__c = 123456;
        trans.FinServ__TransactionType__c='Credit' ;
        insert trans;
        Test.startTest();
        TransactionGraphsApexController.getTransaction(trans.Id);
        System.assertEquals(1, 1);
        Test.stopTest();
    }
}