src/objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>401K</fullName>
                </value>
                <value>
                    <fullName>529 Account</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>CD</fullName>
                </value>
                <value>
                    <fullName>Checking</fullName>
                </value>
                <value>
                    <fullName>IRA</fullName>
                </value>
                <value>
                    <fullName>Money Market</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Retail Brokerage</fullName>
                </value>
                <value>
                    <fullName>Roth IRA</fullName>
                </value>
                <value>
                    <fullName>Saving</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>Debt</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinServ__Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__LoanAmount__c</fullName>
        <inlineHelpText>Kindly fill this field for your Loan</inlineHelpText>
        <label>Loan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialAccountTransaction__c.object
<CustomObject>
    <description>Represents information about financial account transactions.</description>
    <fields>
        <fullName>FinServ__Amount__c</fullName>
        <description>The amount of each transaction. This field is used for reconciliation.</description>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__FinancialAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account</label>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Account Transactions</relationshipLabel>
        <relationshipName>FinancialAccountTranslations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__TransactionDate__c</fullName>
        <description>The date each transaction occurred. This field is used for reconciliation.</description>
        <label>Transaction Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FinServ__TransactionType__c</fullName>
        <description>Type of the transaction. This field is used to determine whether the transaction falls under income or expense. Also used in reconciliation logic.</description>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Debit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Financial Account Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/UpdateFinancialAccountBalanceTest.cls
@isTest 
public class UpdateFinancialAccountBalanceTest {
    
     @testSetup static void setup(){
        String namespace= NamespaceUtility.returnNamespace();
        
        Id devRecordTypeId = [select Id,DeveloperName  from RecordType where sObjectType='Account' AND DeveloperName='IndustriesIndividual'].Id;
        
        Account a=new Account(Name='test', RecordTypeId=devRecordTypeId);
        insert a;
        List<FinServ__FinancialAccount__c> fa=new List<FinServ__FinancialAccount__c>();
        fa.add(new FinServ__FinancialAccount__c(Name='testfa',FinServ__Balance__c=2000, FinServ__PrimaryOwner__c=a.Id, Account_Type__c='Savings'));
        fa.add(new FinServ__FinancialAccount__c(Name='testfl',FinServ__LoanAmount__c=2000, FinServ__PrimaryOwner__c=a.Id, Account_Type__c='Loan'));
        
        insert fa;
       
        
        List<FinServ__FinancialAccountTransaction__c> fat=new List<FinServ__FinancialAccountTransaction__c>();
        fat.add(new FinServ__FinancialAccountTransaction__c(FinServ__Amount__c=2000, FinServ__TransactionDate__c=Date.today(),FinServ__TransactionType__c='Credit',FinServ__FinancialAccount__c=fa[0].Id));
        fat.add(new FinServ__FinancialAccountTransaction__c(FinServ__Amount__c=2000, FinServ__TransactionDate__c=Date.today(),FinServ__TransactionType__c='Debit',FinServ__FinancialAccount__c=fa[0].Id));
        fat.add(new FinServ__FinancialAccountTransaction__c(FinServ__Amount__c=2000, FinServ__TransactionDate__c=Date.today(),FinServ__FinancialAccount__c=fa[1].Id));
        
        insert fat;
        
        
    }
    
    @isTest
    static void insertTransactionSavingCredit(){
        String ids=[Select Id from FinServ__FinancialAccount__c where Name='testfa' LIMIT 1].Id;
          FinServ__FinancialAccountTransaction__c f=new FinServ__FinancialAccountTransaction__c(FinServ__Amount__c=2000, FinServ__TransactionDate__c=Date.today(),FinServ__TransactionType__c='Credit',FinServ__FinancialAccount__c=ids);
       insert f;
        System.assert(f.Id!=null);
        
    }
    
     @isTest
    static void insertTransactionLoanCredit(){
        String ids=[Select Id from FinServ__FinancialAccount__c where Name='testfl' LIMIT 1].Id;
          FinServ__FinancialAccountTransaction__c f=new FinServ__FinancialAccountTransaction__c(FinServ__Amount__c=2000, FinServ__TransactionDate__c=Date.today(),FinServ__TransactionType__c='Credit',FinServ__FinancialAccount__c=ids);
       insert f;
        System.assert(f.Id!=null);
        
    }
     @isTest
    static void insertTransactionSavingDebit(){
        String ids=[Select Id from FinServ__FinancialAccount__c where Name='testfa' LIMIT 1].Id;
          FinServ__FinancialAccountTransaction__c f=new FinServ__FinancialAccountTransaction__c(FinServ__Amount__c=2000, FinServ__TransactionDate__c=Date.today(),FinServ__FinancialAccount__c=ids,FinServ__TransactionType__c='Debit');
       insert f;
        System.assert(f.Id!=null);
        
    }
    
     @isTest
    static void insertTransactionLoanDebit(){
        String ids=[Select Id from FinServ__FinancialAccount__c where Name='testfl' LIMIT 1].Id;
          FinServ__FinancialAccountTransaction__c f=new FinServ__FinancialAccountTransaction__c(FinServ__Amount__c=2000, FinServ__TransactionDate__c=Date.today(),FinServ__FinancialAccount__c=ids,FinServ__TransactionType__c='Debit');
       insert f;
        System.assert(f.Id!=null);
        
    }
    @isTest
    static void updateTransactionCredit(){
        FinServ__FinancialAccountTransaction__c f=[Select Id,FinServ__Amount__c from FinServ__FinancialAccountTransaction__c where FinServ__TransactionType__c='Credit' LIMIT 1];
        f.FinServ__Amount__c=20000;
        update f;
    }
    @isTest
    static void updateTransactionDebit(){
        FinServ__FinancialAccountTransaction__c f=[Select Id,FinServ__Amount__c from FinServ__FinancialAccountTransaction__c where FinServ__TransactionType__c='Debit' LIMIT 1];
        f.FinServ__Amount__c=20000;
        update f;
    }

    @isTest
    static void deleteTransactionCredit(){
        FinServ__FinancialAccountTransaction__c f=[Select Id,FinServ__Amount__c from FinServ__FinancialAccountTransaction__c where FinServ__TransactionType__c='Credit' LIMIT 1];
        delete f;
    }
    
     @isTest
    static void deleteTransactionDebit(){
        FinServ__FinancialAccountTransaction__c f=[Select Id,FinServ__Amount__c from FinServ__FinancialAccountTransaction__c where FinServ__TransactionType__c='Debit' LIMIT 1];
        delete f;
    }
    

}