src/objects/FinServ__AssetsAndLiabilities__c.object
<CustomObject>
    <description>Assets or liabilities that are not represented in a client&apos;s financial accounts, such as real estate or collectibles.</description>
    <fields>
        <fullName>FinServ__Amount__c</fullName>
        <description>Amount of an asset (positive) or liability (negative).</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__AssetsAndLiabilitiesType__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Auto Loan</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Personal Loan</fullName>
                </value>
                <value>
                    <fullName>Real Estate</fullName>
                </value>
                <value>
                    <fullName>Equipment</fullName>
                </value>
                <value>
                    <fullName>Automobile</fullName>
                </value>
                <value>
                    <fullName>Collection</fullName>
                </value>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>Jewelry</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinServ__FinancialAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Financial account that this asset or liability is related to.</description>
        <label>Financial Account</label>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Assets and Liabilities</relationshipLabel>
        <relationshipName>AssetsAndLiabilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__JointOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Joint Owner</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>IndustriesIndividual</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Joint Owner</relationshipLabel>
        <relationshipName>JointOwner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Assets and Liabilities</relationshipLabel>
        <relationshipName>ClientAssetsAndLiabilities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Assets and Liabilities</label>
    <nameField>
        <label>Asset or Liability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets and Liabilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>401K</fullName>
                </value>
                <value>
                    <fullName>529 Account</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>CD</fullName>
                </value>
                <value>
                    <fullName>Checking</fullName>
                </value>
                <value>
                    <fullName>IRA</fullName>
                </value>
                <value>
                    <fullName>Money Market</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Retail Brokerage</fullName>
                </value>
                <value>
                    <fullName>Roth IRA</fullName>
                </value>
                <value>
                    <fullName>Saving</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>Debt</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinServ__Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__JointOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Joint Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Joint Owner</relationshipLabel>
        <relationshipName>FAJointOwner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/updateOfFinancialAccount.cls
@isTest
public class updateOfFinancialAccount {
@isTest
    static void TestDeleteAccountWithOneOpportunity() {
        
        List<FinServ__AssetsAndLiabilities__c> c=new List<FinServ__AssetsAndLiabilities__c>();
        Account ac=new Account();
        ac.Name='Test Account';
       	ac.RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        insert ac;
        
        Account ac1=new Account();
        ac1.Name='Test Account2';
       	ac1.RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        insert ac1;
        
        FinServ__FinancialAccount__c fa=new FinServ__FinancialAccount__c();
        fa.RecordTypeId=Schema.SObjectType.FinServ__FinancialAccount__c.getRecordTypeInfosByName().get('Bank Account').getRecordTypeId();
        fa.Account_Type__c='Savings';
        fa.FinServ__Balance__c=5000;
        fa.FinServ__PrimaryOwner__c=ac.Id;
  //      fa.FinServ__JointOwner__c=ac1.Id;
        fa.Name='FaName';
        insert fa;
        
        FinServ__FinancialAccount__c fa1=new FinServ__FinancialAccount__c();
        fa1.RecordTypeId=Schema.SObjectType.FinServ__FinancialAccount__c.getRecordTypeInfosByName().get('Bank Account').getRecordTypeId();
        fa1.Account_Type__c='401K';
        fa1.FinServ__Balance__c=6000;
        fa1.FinServ__PrimaryOwner__c=ac1.Id;
  //      fa.FinServ__JointOwner__c=ac1.Id;
        fa1.Name='FaName1';
        insert fa1;
        
        FinServ__FinancialAccount__c fa2=new FinServ__FinancialAccount__c();
        fa2.RecordTypeId=Schema.SObjectType.FinServ__FinancialAccount__c.getRecordTypeInfosByName().get('Bank Account').getRecordTypeId();
        fa2.Account_Type__c='Checking';
        fa2.FinServ__Balance__c=7000;
        fa2.FinServ__PrimaryOwner__c=ac1.Id;
  //      fa.FinServ__JointOwner__c=ac1.Id;
        fa2.Name='FaName2';
        insert fa2;
        
        FinServ__FinancialAccount__c fa3=new FinServ__FinancialAccount__c();
        fa3.RecordTypeId=Schema.SObjectType.FinServ__FinancialAccount__c.getRecordTypeInfosByName().get('Bank Account').getRecordTypeId();
      //  fa3.Account_Type__c='Checking';
        fa3.FinServ__Balance__c=7000;
        fa3.FinServ__PrimaryOwner__c=ac1.Id;
  //      fa.FinServ__JointOwner__c=ac1.Id;
        fa3.Name='FaName3';
        insert fa3;
        
        FinServ__AssetsAndLiabilities__c ast=new FinServ__AssetsAndLiabilities__c();
        ast.FinServ__FinancialAccount__c=fa.Id;
        ast.FinServ__Amount__c=fa.FinServ__Balance__c;
        ast.FinServ__PrimaryOwner__c=fa.FinServ__PrimaryOwner__c;
        ast.FinServ__AssetsAndLiabilitiesType__c='cash';
        ast.Name=fa.Name;
        insert ast;
        
        FinServ__AssetsAndLiabilities__c ast1=new FinServ__AssetsAndLiabilities__c();
        ast1.FinServ__FinancialAccount__c=fa1.Id;
        ast1.FinServ__Amount__c=fa1.FinServ__Balance__c;
        ast1.FinServ__PrimaryOwner__c=fa1.FinServ__PrimaryOwner__c;
        ast1.FinServ__AssetsAndLiabilitiesType__c='Bonds';
        ast1.Name=fa1.Name;
        insert ast1;
        
        FinServ__AssetsAndLiabilities__c ast2=new FinServ__AssetsAndLiabilities__c();
        ast2.FinServ__FinancialAccount__c=fa2.Id;
        ast2.FinServ__Amount__c=fa2.FinServ__Balance__c;
        ast2.FinServ__PrimaryOwner__c=fa2.FinServ__PrimaryOwner__c;
        ast2.FinServ__AssetsAndLiabilitiesType__c='Stocks';
        ast2.Name=fa2.Name;
        insert ast2;
        
        FinServ__AssetsAndLiabilities__c ast3=new FinServ__AssetsAndLiabilities__c();
        ast3.FinServ__FinancialAccount__c=fa3.Id;
        ast3.FinServ__Amount__c=fa3.FinServ__Balance__c;
        ast3.FinServ__PrimaryOwner__c=fa3.FinServ__PrimaryOwner__c;
        ast3.FinServ__AssetsAndLiabilitiesType__c='Others';
        ast3.Name=fa3.Name;
        insert ast3;
        
        Database.DeleteResult result = Database.delete(fa, false);
        
        c.add(ast);
        c.add(ast1);
        c.add(ast2);
         c.add(ast3);
    }
}