src/objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>FinServ__APY__c</fullName>
        <inlineHelpText>Kindly fill the Annual Yield Rate for this Financial Account. Do not leave this blank.</inlineHelpText>
        <label>APY</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>FinServ__Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FinServ__FinancialGoal__c.object
<CustomObject>
    <description>Tracks a client&apos;s goal.</description>
    <fields>
        <fullName>Associated_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Associated Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3 AND 4</booleanFilter>
            <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Scenario_Credit_Cards_Record_Type</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Scenario_Loans_Record_Type</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>LoanAccount</value>
            </filterItems>
            <filterItems>
                <field>FinServ__FinancialAccount__c.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>CreditCard</value>
            </filterItems>
            <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Goals</relationshipLabel>
        <relationshipName>Financial_Goals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>IndustriesIndividual</value>
            </filterItems>
            <filterItems>
                <field>Account.FinServ__IndividualType__c</field>
                <operation>equals</operation>
                <value>Individual</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Financial Goals</relationshipLabel>
        <relationshipName>ClientFinancialGoals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__TargetDate__c</fullName>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Goal_Priority__c</fullName>
        <label>Goal Priority</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Priority 1 (must have)</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Priority 2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Priority 3</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Required_Monthly_Saving__c</fullName>
        <label>Required Monthly Saving</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Value__c</fullName>
        <label>Start Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Goal</label>
    <nameField>
        <label>Financial Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Nonretirementgoalapexcontrollertest.cls
@isTest
public class Nonretirementgoalapexcontrollertest {
    @testSetup
    static void testmethod1()
    {
        Account acc1 = new Account();
        acc1.Name = 'test account 1';
        
         Account acc2 = new Account();
        acc2.Name = 'test account 2';
        
        list<RecordType> rcc1 =[Select Id From RecordType Where SobjectType='Account' And Name='Individual' limit 1];
        acc1.RecordTypeId = rcc1[0].Id;
        acc2.RecordTypeId = rcc1[0].Id;
        
        insert acc1;
        insert acc2;
        
        Account acc = [Select id from Account where Name='test account 1'];
        FinServ__FinancialAccount__c financial1 = new FinServ__FinancialAccount__c();
        financial1.Name = 'test financial account 1';
        list<RecordType> rcc =[Select Id From RecordType Where SobjectType='FinServ__FinancialAccount__c' And Name='Bank Account' limit 1];
        financial1.RecordtypeId = rcc[0].Id;
        financial1.FinServ__Balance__c = 567;
        financial1.FinServ__PrimaryOwner__c= acc.Id;
        financial1.FinServ__APY__c = 3;
        insert financial1;
        
         Account acco = [Select id from Account where Name='test account 2'];
        FinServ__FinancialAccount__c financial2 = new FinServ__FinancialAccount__c();
        financial2.Name = 'test financial account 2';
        financial2.RecordtypeId = rcc[0].Id;
        financial2.FinServ__Balance__c = 5627;
        financial2.FinServ__PrimaryOwner__c= acco.Id;
        financial2.FinServ__APY__c = 0;
        insert financial2;
        
        
        FinServ__FinancialGoal__c goal1 = new FinServ__FinancialGoal__c();
        goal1.Name = 'test goal 1';
        goal1.Associated_Account__c = financial1.Id;
        goal1.Required_Monthly_Saving__c = 0;
        goal1.Start_Date__c = date.today();
        goal1.Start_Value__c = 456700;
        goal1.FinServ__TargetDate__c = date.today()+90;
        goal1.FinServ__PrimaryOwner__c=acc.Id;
          goal1.Goal_Priority__c = 'Priority 2';
        insert goal1;
        
         FinServ__FinancialGoal__c goal2 = new FinServ__FinancialGoal__c();
        goal2.Name = 'test goal 2';
        goal2.Associated_Account__c = financial2.Id;
        goal2.Required_Monthly_Saving__c =3456000;
        goal2.Start_Date__c = date.today();
        goal2.Start_Value__c = 4567;
        goal2.FinServ__TargetDate__c = date.today()+90;
        goal2.FinServ__PrimaryOwner__c=acco.Id;
          goal2.Goal_Priority__c = 'Priority 2';
        insert goal2;
    }
    
    static testMethod void nonretirementtestapex()
    {  
        Account a=[select id  from Account where name = 'test account 1'];
        
        FinServ__FinancialAccount__c fAcc1 = [select id  from FinServ__FinancialAccount__c where name = 'test financial account 1'];
        FinServ__FinancialGoal__c fGoal1 = [select FinServ__TargetDate__c,Start_Value__c,Required_Monthly_Saving__c from FinServ__FinancialGoal__c where name = 'test goal 1' ];
        DateTime d = fGoal1.FinServ__TargetDate__c;
        String targetDate = d.format('YYYY-MM-dd');
        String targetAmt = String.valueOf(fGoal1.Required_Monthly_Saving__c);
        String currentAmount  = String.valueOf(fGoal1.Start_Value__c);
        
        FinServ__FinancialAccount__c fAcc2 = [select id  from FinServ__FinancialAccount__c where name = 'test financial account 2'];
        FinServ__FinancialGoal__c fGoal2 = [select FinServ__TargetDate__c,Start_Value__c,Required_Monthly_Saving__c from FinServ__FinancialGoal__c where name = 'test goal 2' ];
        DateTime dt = fGoal2.FinServ__TargetDate__c;
        String tarDate = dt.format('YYYY-MM-dd');
        String tarAmt = String.valueOf(fGoal2.Required_Monthly_Saving__c);
        String currAmount  = String.valueOf(fGoal2.Start_Value__c);
        
        Test.startTest();
        Nonretirementgoalapexcontroller.dample(a.Id);
Nonretirementgoalapexcontroller.getNonRetirementGoalRecord(fGoal2.Id)     ;   
        Nonretirementgoalapexcontroller.getCurrentAmount(fAcc1.id ,targetDate, targetAmt,currentAmount );
        Nonretirementgoalapexcontroller.getCurrentAmount(fAcc2.id ,tarDate, tarAmt,currAmount );
        Nonretirementgoalapexcontroller.getCurrentAmount(fAcc2.id ,tarDate, tarAmt,'0');
        Nonretirementgoalapexcontroller.getCurrentAmount(null ,tarDate, tarAmt,'0');
        Nonretirementgoalapexcontroller.getCurrentAmount(fAcc2.id ,tarDate, '123','123' );
                Nonretirementgoalapexcontroller.getCurrentAmount(fAcc2.id ,null, tarAmt,null );
       
        Test.stopTest(); 
        
        
        System.assertEquals('1', '1');
    }
    
}