src/objects/FinServ__FinancialGoal__c.object
<CustomObject>
    <description>Tracks a client&apos;s goal.</description>
    <fields>
        <fullName>FinServ__ActualValue__c</fullName>
        <label>Actual Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__CompletionDate__c</fullName>
        <label>Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FinServ__TargetDate__c</fullName>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FinServ__TargetValue__c</fullName>
        <label>Target Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Goal</label>
    <nameField>
        <label>Financial Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/GoalValueApex.cls
public class GoalValueApex {
 @AuraEnabled
    public static List<FinServ__FinancialGoal__c> getTotalGoal(){
        List<FinServ__FinancialGoal__c> gl=new List<FinServ__FinancialGoal__c>();
        gl=[select id ,Name ,FinServ__ActualValue__c,FinServ__CompletionDate__c,FinServ__TargetDate__c,FinServ__TargetValue__c from FinServ__FinancialGoal__c  Where createdById=:UserInfo.getUserId()];
        return gl;   
    }
}